### ISSUE TITLE
Critical error on L043 when there is a coalesce in inside the case statement

### ISSUE THREAD

**Issue by pwildenhain** [sqlfluff/sqlfluff#2055] opened 2021-12-06 16:16 UTC
## Expected Behaviour

No critical errors

## Observed Behaviour

`test.sql`
```sql
select
    field_1,
    field_2,
    field_3,
    case
        when coalesce(field_2, field_3) is null then 1 else 0
    end as field_4
from my_table
```

```sh
$ sqlfluff lint test.sql 
CRITICAL   [L043] Applying rule L043 threw an Exception:                                                                                                    
Traceback (most recent call last):
  File "/Users/wildenhaip/Documents/drive/.venv/lib/python3.9/site-packages/sqlfluff/core/rules/base.py", line 324, in crawl
    res = self._eval(
  File "/Users/wildenhaip/Documents/drive/.venv/lib/python3.9/site-packages/sqlfluff/rules/L043.py", line 218, in _eval
    column_reference_segment = next(
StopIteration
== [test.sql] FAIL                                                                                                                                          
L:   5 | P:   5 | L043 | Unexpected exception: ; Could you open an issue at
                       | https://github.com/sqlfluff/sqlfluff/issues ? You can
                       | ignore this exception for now, by adding '--noqa: L043'
                       | at the end of line 5
All Finished 📜 🎉!
```

## Dialect

ANSI

## Version
Include the output of `sqlfluff --version` along with your Python version

```sh
$ sqlfluff --version && python --version
sqlfluff, version 0.8.2
Python 3.9.6
```

## Configuration

None

**Comment by jpy-git** [comment] 2021-12-06 16:40
@pwildenhain closing as it's a duplicate of #2047. I'm going to take a look at these later today 👍

**Closed** 2021-12-06 16:40 UTC
Labels: bug, rule bug
