### ISSUE TITLE
Support postgress functionn array arguments for user defined type

### ISSUE THREAD

**Issue by MikaelCall** [sqlfluff/sqlfluff#2093] opened 2021-12-11 10:00 UTC
## Expected Behaviour

SQLFluff should be able to parse a function/procedure argument that is an array of a user defined type.

## Observed Behaviour

```shell
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    statement:
[L:  1, P:  1]      |        create_type_statement:
[L:  1, P:  1]      |            keyword:                                          'CREATE'
[L:  1, P:  7]      |            whitespace:                                       ' '
[L:  1, P:  8]      |            keyword:                                          'TYPE'
[L:  1, P: 12]      |            whitespace:                                       ' '
[L:  1, P: 13]      |            object_reference:
[L:  1, P: 13]      |                identifier:                                   'int_code_type'
[L:  1, P: 26]      |            whitespace:                                       ' '
[L:  1, P: 27]      |            keyword:                                          'AS'
[L:  1, P: 29]      |            whitespace:                                       ' '
[L:  1, P: 30]      |            bracketed:
[L:  1, P: 30]      |                start_bracket:                                '('
[L:  1, P: 31]      |                [META] indent:
[L:  1, P: 31]      |                raw:                                          'code'
[L:  1, P: 35]      |                whitespace:                                   ' '
[L:  1, P: 36]      |                raw:                                          'INTEGER'
[L:  1, P: 43]      |                comma:                                        ','
[L:  1, P: 44]      |                whitespace:                                   ' '
[L:  1, P: 45]      |                raw:                                          'text_sv'
[L:  1, P: 52]      |                whitespace:                                   ' '
[L:  1, P: 53]      |                raw:                                          'TEXT'
[L:  1, P: 57]      |                [META] dedent:
[L:  1, P: 57]      |                end_bracket:                                  ')'
[L:  1, P: 58]      |    statement_terminator:                                     ';'
[L:  1, P: 59]      |    newline:                                                  '\n'
[L:  2, P:  1]      |    newline:                                                  '\n'
[L:  3, P:  1]      |    statement:
[L:  3, P:  1]      |        unparsable:                                           !! Expected: 'StatementSegment'
[L:  3, P:  1]      |            raw:                                              'CREATE'
[L:  3, P:  7]      |            whitespace:                                       ' '
[L:  3, P:  8]      |            raw:                                              'PROCEDURE'
[L:  3, P: 17]      |            whitespace:                                       ' '
[L:  3, P: 18]      |            raw:                                              'update_codes'
[L:  3, P: 30]      |            newline:                                          '\n'
[L:  4, P:  1]      |            bracketed:
[L:  4, P:  1]      |                start_bracket:                                '('
[L:  4, P:  2]      |                newline:                                      '\n'
[L:  5, P:  1]      |                whitespace:                                   '  '
[L:  5, P:  3]      |                raw:                                          'codes'
[L:  5, P:  8]      |                whitespace:                                   ' '
[L:  5, P:  9]      |                raw:                                          'int_code_type'
[L:  5, P: 22]      |                start_square_bracket:                         '['
[L:  5, P: 23]      |                end_square_bracket:                           ']'
[L:  5, P: 24]      |                newline:                                      '\n'
[L:  6, P:  1]      |                end_bracket:                                  ')'
[L:  6, P:  2]      |            newline:                                          '\n'
[L:  7, P:  1]      |            raw:                                              'AS'
[L:  7, P:  3]      |            newline:                                          '\n'
[L:  8, P:  1]      |            raw:                                              '$$\nBEGIN\n    RETURN;\nEND;\n$$'
[L: 12, P:  3]      |            whitespace:                                       ' '
[L: 12, P:  4]      |            raw:                                              'LANGUAGE'
[L: 12, P: 12]      |            whitespace:                                       ' '
[L: 12, P: 13]      |            raw:                                              'plpgsql'
[L: 12, P: 20]      |    statement_terminator:                                     ';'
[L: 12, P: 21]      |    newline:                                                  '\n'

==== parsing violations ====
L:   3 | P:   1 |  PRS | Line 3, Position 1: Found unparsable section: 'CREATE PROCEDURE
                       | update_codes\n(\n codes ...'
```

## Steps to Reproduce

```sql
CREATE TYPE int_code_type AS (code INTEGER, text_sv TEXT);

CREATE PROCEDURE update_codes
(
  codes int_code_type[]
)
AS
$$
BEGIN
    RETURN;
END;
$$ LANGUAGE plpgsql;
```

## Dialect

`postgres`

## Version

```
sqlfluff, version 0.8.2
Python 3.8.10
```

## Configuration

```
N/A : Default configuration
```

**Comment by MikaelCall** [comment] 2021-12-14 07:03
I've upgraded to 0.9.0 and this still does not parse.

**Comment by tunetheweb** [comment] 2022-01-23 23:38
This is a duplicate of #2092 and it's the `CREATE PROCEDURE` which is causing the problem rather than any function array arguments for user defined type. It parses fine in the #2441 branch. Closing as duplicate.

**Closed by tunetheweb** 2022-01-23 23:38 UTC
Labels: bug, postgres
