### ISSUE TITLE
SQLFluff Fix doesn't always fix indentation on join syntax

### ISSUE THREAD

**Issue by WittierDinosaur** [sqlfluff/sqlfluff#2012] opened 2021-11-30 17:04 UTC
Join indentation isn't properly fixed when over-indented

## Expected Behaviour

```
SELECT a.a
FROM a
LEFT JOIN b
          ON
    b.thing = a.thing
    AND b.x = a.x;

```

should fix to

```
SELECT a.a
FROM a
LEFT JOIN b
    ON b.thing = a.thing
    AND b.x = a.x;

```

Though removing the newline between the ON and condition isn't necessarily relevant to this bug - this would do:

```
SELECT a.a
FROM a
LEFT JOIN b
    ON 
    b.thing = a.thing
    AND b.x = a.x;

```

## Observed Behaviour

Fix doesn't change the indentation

## Steps to Reproduce

sqlfluff fix with default config

## Dialect

ansi

## Version
0.8.2

## Configuration
Default

**Comment by tunetheweb** [comment] 2021-12-04 14:30
This is interesting. It doesn't consider this over indented. If you change it to this:

```sql
SELECT a.a
FROM a
LEFT JOIN b
           ON
    b.thing = a.thing
    AND b.x = a.x;
```

It will fix it to your original SQL.

Basically it considers the below equally valid indentation:

```sql
-- align on table
LEFT JOIN b
          ON b.thing = a.thing

-- align on 4 spaces
LEFT JOIN b
    ON b.thing = a.thing
```

**Comment by WittierDinosaur** [comment] 2021-12-11 12:56
@tunetheweb Do you consider this a bug? I think at the very least it's inconsistent, and I'm of a mind that it is a bug (as the user select an indentation amount for their config - I don't think it should ignore it in this case)

**Comment by tunetheweb** [comment] 2021-12-11 13:00
Potentially. It's depends on whether you consider "align on table" as zero indentation or incorrect indentation of 10.

I'd be curious as to HOW SQLFluff knows to indent to the table before I answer the question definitively. And maybe there should be a config option (perhaps the default one!) to just use the user space indentation and no other.

**Comment by barrywhart** [comment] 2022-01-10 21:35
In the [two examples provided above](https://github.com/sqlfluff/sqlfluff/issues/2012#issuecomment-986036996) by @tunetheweb, I think the first is called "hanging indent". while the second is a more conventional indent. This is similar to a common thing in, say, Python, where it is common to indent code two ways:
```
def my_function(a,
               b,
               c
):

def my_function(
    a,
    b,
    c
):
```

**Comment by barrywhart** [comment] 2022-01-10 21:39
Before attempting to "fix" this, we should review and understand the hanging indent behavior and define what we're looking to change, e.g. _remove_ hanging indent? Or _limit_ the situations where L003 will consider it? E.g., maybe only for situations where the section is bracketed (i.e. parentheses)? Or something else?

Tagging @NiallRees for awareness, as he is thinking about the future direction for automatic formatting and indentation for SQLFluff.

**Comment by tunetheweb** [comment] 2022-01-24 01:21
I'm going to close this as working as intended. There's all sorts of code about hanging indents in L003.

It's possible we should add an option to ignore hanging indents (if which case feel free to reopen if you think we should do this) but at the moment this is working as intended.

**Closed by tunetheweb** 2022-01-24 01:21 UTC
Labels: bug, rule bug
