### ISSUE TITLE
load_macros_from_path should allow exceptions

### ISSUE THREAD

**Issue by olhmr** [sqlfluff/sqlfluff#381] opened 2020-06-10 08:12 UTC
### Context
We are working with `dbt` in BigQuery and, as part of that, have created a new materialization strategy to handle some use cases that weren't properly addressed by built-in `dbt` options. This means that we have a macro in our macros folder containing this line: 
```
{% materialization incremental, adapter='bigquery' -%}
```

### Issue
The `materialization` tag is not recognised, giving this error: 
```
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'materialization'
``` 
Clearly, one solution would be to add a jinja extension that covers this tag, which I definitely would appreciate, but since there's always a risk of this scenario cropping up it seems there should be an option to exclude certain paths from the `load_macros_from_path` statement in ```[sqlfluff:templater:jinja]```. 

Alternatively, being able to specify multiple paths would be nice, since then we could add all the subfolders in our `macros` directory except for the one causing the error.

**Comment by alanmcruickshank** [comment] 2020-08-07 11:47
Yeah this is a challenging one. It's becoming increasingly difficult to support a wide set of dbt extensions and macros. I'm considering changing how we support the compiling of templates and actually getting dbt to do the rendering of queries, which would solve a load of these issues.

Any ideas on how we might go about fixing this one?

**Comment by pwildenhain** [comment] 2020-10-03 17:38
> I'm considering changing how we support the compiling of templates and actually getting dbt to do the rendering of queries, which would solve a load of these issues.

I'm 💯 in agreement with this. If people are using `dbt` _anyway_ with this project, then I think we should just use `dbt` to compile the queries, and eliminate the need to double document macros

Could this be added as a config option? Should this be a separate plugin (like `sqlfluff-dbt`)?

**Comment by pwildenhain** [comment] 2020-10-03 20:53
Also, possible duplicate of #371

**Comment by noahbruegmann** [comment] 2020-10-26 17:56
Big +1 to this. Same problem occurs with some other functionality like snapshots.

**Comment by alanmcruickshank** [comment] 2020-11-26 13:54
I'm going to suggest that this is best achieved with the new `dbt` templater built into sqlfluff.

For people watching this issue (@noahbruegmann , @dmateusp , @KimchaC , @olhmr ), there is now an alpha release of sqlfluff 0.4.0 available on pypi (https://pypi.org/project/sqlfluff/0.4.0a1/).

I would be very grateful for feedback on the work that @dmateusp has done to get us this far as part of #508 .

In particular you can find docs for the new dbt templater here: https://docs.sqlfluff.com/en/latest/configuration.html#dbt-project-configuration

It would be useful to know whether:
a) the feature satisfies all the requirements here
b) whether the current implementation works in production
b) whether the documentation that we've got is sufficient for users to set things up

**Comment by NiallRees** [comment] 2021-01-26 17:02
Going to close this as believe it is solved by the new dbt templater :)

**Closed by NiallRees** 2021-01-26 17:02 UTC
Labels: bug, duplicate, help wanted, templating

**Comment by noahbruegmann** [comment] 2021-01-26 17:34
I can confirm that we've been testing this on a few different projects now and it seems to be working well. Thanks!
