### ISSUE TITLE
dbt linting encounters RuntimeError related to builtin.sql file

### ISSUE THREAD

**Issue by dlawrences** [sqlfluff/sqlfluff#2261] opened 2022-01-08 20:37 UTC
I am trying to run the dbt linter (sqlfluff-templater-dbt) inside a CI process. While attempting to lint, the linter runs into an error that I haven't been able to circumvent.

## Expected Behaviour

```sh
poetry run sqlfluff lint
```

completes successfully.

## Observed Behaviour

```sh
  poetry run sqlfluff lint
  shell: /usr/bin/bash -e {0}
  env:
    DBT_PROFILES_DIR: ./
    SNOWFLAKE_ACCOUNT: ***
    SNOWFLAKE_USERNAME: ***
    SNOWFLAKE_PASSWORD: ***
    SNOWFLAKE_ROLE: ***
    SNOWFLAKE_DATABASE: ***
    SNOWFLAKE_SCHEMA: ***
    SNOWFLAKE_WAREHOUSE: ***
    PYENV_ROOT: /opt/hostedtoolcache/pyenv_root/1.2.21/x64
=== [dbt templater] Sorting Nodes...
20:03:39  Partial parse save file not found. Starting full parse.
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
Traceback (most recent call last):
  File "/home/runner/work/data-platform/data-platform/.venv/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/home/runner/work/data-platform/data-platform/.venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/work/data-platform/data-platform/.venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/runner/work/data-platform/data-platform/.venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/runner/work/data-platform/data-platform/.venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/work/data-platform/data-platform/.venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/work/data-platform/data-platform/.venv/lib/python3.8/site-packages/sqlfluff/cli/commands.py", line 480, in lint
    result = lnt.lint_paths(
  File "/home/runner/work/data-platform/data-platform/.venv/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 964, in lint_paths
    self.lint_path(
  File "/home/runner/work/data-platform/data-platform/.venv/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 916, in lint_path
    for i, linted_file in enumerate(runner.run(fnames, fix), start=1):
  File "/home/runner/work/data-platform/data-platform/.venv/lib/python3.8/site-packages/sqlfluff/core/linter/runner.py", line 101, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/home/runner/work/data-platform/data-platform/.venv/lib/python3.8/site-packages/sqlfluff/core/linter/runner.py", line 54, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/home/runner/work/data-platform/data-platform/.venv/lib/python3.8/site-packages/sqlfluff/core/linter/runner.py", line 43, in iter_rendered
    yield fname, self.linter.render_file(fname, self.config)
  File "/home/runner/work/data-platform/data-platform/.venv/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 642, in render_file
    return self.render_string(raw_file, fname, config, encoding)
  File "/home/runner/work/data-platform/data-platform/.venv/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 619, in render_string
    templated_file, templater_violations = self.templater.process(
  File "/home/runner/work/data-platform/data-platform/.venv/lib/python3.8/site-packages/sqlfluff_templater_dbt/templater.py", line 330, in process
    processed_result = self._unsafe_process(fname_absolute_path, in_str, config)
  File "/home/runner/work/data-platform/data-platform/.venv/lib/python3.8/site-packages/sqlfluff_templater_dbt/templater.py", line 447, in _unsafe_process
    node = self._find_node(fname, config)
  File "/home/runner/work/data-platform/data-platform/.venv/lib/python3.8/site-packages/sqlfluff_templater_dbt/templater.py", line 402, in _find_node
    raise RuntimeError(
RuntimeError: File /home/runner/work/data-platform/data-platform/.venv/lib/python3.8/site-packages/dbt/include/global_project/tests/generic/builtin.sql was not found in dbt project
Error: Process completed with exit code 1.
```

## Steps to Reproduce

The repository has the following structure:

```
.
├── src
│   ├── projects
│   │   └── dbt_project_name
│   ├── subfolder_1
│   ├── subfolder_2
│   ├── subfolder_3
│   ├── subfolder_4
│   ├── subfolder_5
│   └── subfolder_6
├── templates
│   ├── subfolder_1
│   ├── subfolder_2
│   ├── subfolder_3
│   └── subfolder_4
└── terraform
    ├── modules
    ├── subfolder_1
    ├── subfolder_2
    └── subfolder_3
```

sqlfluff is run inside a poetry python environment with the following specification:

```
[tool.poetry]
name = "data-platform"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "^3.8"
yamllint = "^1.26.3"
sqlfluff-templater-dbt = "^0.9.0"
dbt-snowflake = "^1.0.0"
dbt-core = "^1.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

## Dialect

```
[sqlfluff]
verbose = 5
dialect = snowflake
templater = dbt
```

## Version

```sh
poetry show
dbt-core                   1.0.1      With dbt, data analysts and engineers can build analytics the way engineers build applications.
dbt-extractor              0.4.0
dbt-snowflake              1.0.0      The Snowflake adapter plugin for dbt
sqlfluff                   0.9.0      The SQL Linter for Humans
sqlfluff-templater-dbt     0.9.0      Lint your dbt project SQL
```

## Configuration

```
#.sqlfluff
[sqlfluff]
verbose = 5
dialect = snowflake
templater = dbt

[sqlfluff:rules]
tab_space_size = 4

[sqlfluff:templater:dbt]
project_dir = ./src/projects/dbt_project_name
profiles_dir = ./
profile = default

[tool.sqlfluff.templater.jinja]
apply_dbt_builtins = True
```

```
#.sqlfluffignore
**target/
**dbt_modules/
**macros/
templates/
terraform/
src/
!src/projects/dbt_project_name
```

### Sample CI action
```yml
# This workflow will install dependencies (from a pyproject.toml file for convenience), lint with a variety of tools
name: YAML & dbt CI

on:
  push:
    branches: [ development ]
    paths: [ 'src/**' ]
  
  pull_request:
    branches: [ development ]
    paths: [ 'src/**' ]

env:
  DBT_PROFILES_DIR: ./
  SNOWFLAKE_ACCOUNT: ${{ secrets.<...>}}
  SNOWFLAKE_USERNAME: ${{ secrets.<...>}}
  SNOWFLAKE_PASSWORD: ${{ secrets.<...> }}
  SNOWFLAKE_ROLE: ${{ secrets.<...> }}
  SNOWFLAKE_DATABASE: ${{ secrets.<...> }}
  SNOWFLAKE_SCHEMA: ${{ secrets.<...> }}
  SNOWFLAKE_WAREHOUSE: ${{ secrets.<...> }}


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get python version
        run: |
          python_version=$(cat .python-version)
          echo "::set-output name=local_python_version::$python_version"
        id: get_python_version

      - name: Setup pyenv
        uses: "gabrielfalcao/pyenv-action@v7"
        with:
          default: ${{ steps.get_python_version.outputs.local_python_version }}
          command: pip install -U pip

      - name: Setup Poetry image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.12
        
      - name: Install Poetry dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install

      - name: Install dbt dependencies
        run: |
          for dir in ./src/projects/*/; do
            if [ -d "$dir" ]; then
              echo "Installing dbt dependencies for ${dir}"
              (cd "$dir" && poetry run dbt deps)
            fi
          done

      - name: Lint with YAMLLint
        if: ${{ false }}
        run: |
          poetry run yamllint . --no-warnings

      - name: Lint with sqlfluff
        run: |
          poetry run sqlfluff lint
```

**Comment by barrywhart** [comment] 2022-01-10 16:51
@dlawrences: Can you provide a more direct example of the issue to help us reproduce it? The info provided is helpful, but it's more of a high-level description than an example: e.g. the directory structure, and CI action are not something a maintainer can directly use to reproduce the problem. It's more like they'd be trying to _recreate_ the problem, which we try to avoid doing, due to the amount of effort and the likelihood we won't manage to reproduce the issue due to missing details.

**Comment by dlawrences** [comment] 2022-01-11 15:02
Thanks for pointing this out, @barrywhart. I managed to get it over the board fortunately, it seems it was a mix of:
- how the lint command was executed
- the configuration of .sqlfluffignore **and where it was placed**
- making sure that all the artifacts of the dbt project were following the actual version of dbt being used (dbt v1 renamed some folders etc which were not consistent across the project)

Final configuration:

```yml
...
- name: Lint with sqlfluff
        run: |
          poetry run sqlfluff lint src/projects/.
```

The .sqlfluff file was placed in the root of the repository (was like this previously as well). This is where the command is being executed from.
```
[sqlfluff]
verbose = 5
dialect = snowflake
templater = dbt

[sqlfluff:rules]
tab_space_size = 4

[sqlfluff:templater:dbt]
project_dir = ./src/projects/dbt_project_name
profiles_dir = .
profile = default

[tool.sqlfluff.templater.jinja]
apply_dbt_builtins = True
```

The .sqlfluffignore file was placed in the actual `dbt_project_name` dbt project folder. I couldn't get it to work while being in the root of the repository.
```ignore
target/
dbt_packages/
macros/
```

I noticed that in https://docs.sqlfluff.com/en/stable/configuration.html#installation-configuration, you guys recommend that .sqlfluff sits where the command is executed from, but it is not clear whether .sqlfluffignore needs to sit somewhere special as well? What I've experienced is that depending on the location of the ignore file, as well as its contents, different macro .sql files would be reported as missing (from dbt itself or from other dependencies). It may be some configuration issue from my side at the end of the day, but I think it's worth a look into the parser of the ignore to figure out if it expects a certain folder structure or not.

**Comment by barrywhart** [comment] 2022-01-11 16:10
@dlawrences: I'm going to close this issue, since you've gotten past your initial problem. Can you take a look at the discussion on this issue to see if it's a duplicate of your `.sqlfluffignore` question? #556

**Closed by barrywhart** 2022-01-11 16:10 UTC
Labels: bug, dbt, awaiting feedback

**Comment by dlawrences** [comment] 2022-01-13 05:42
> @dlawrences: I'm going to close this issue, since you've gotten past your initial problem. Can you take a look at the discussion on this issue to see if it's a duplicate of your `.sqlfluffignore` question? #556

Yes, seems to be a general aspect of how `.sqlfluffignore` is used to identify files/directories to be ignored based on where the command is also executed and the target of the command.
