### ISSUE TITLE
"Connection already closed" when running SQLFluff on folder with .sql files in dbt

### ISSUE THREAD

**Issue by jan-benisek** [sqlfluff/sqlfluff#2302] opened 2022-01-13 14:35 UTC
## Expected Behaviour
Fixing all `.sql` files

## Observed Behaviour
`sqlfluff fix --force --dialect 'redshift' foo/bar/ab_tests`

Get an error during processing of a folder with many sql files. Always crashes on one single file.
Note that all other files in other folders are working.
```
file ab_metrics_accounts_created.sql:  15%|██████████████████████▉                                                                                                                                       | 16/110 [01:37<10:04,  6.43s/it]Traceback (most recent call last):
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/dbt/adapters/postgres/connections.py", line 59, in exception_handler
    yield
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/dbt/adapters/sql/connections.py", line 73, in add_query
    cursor = connection.handle.cursor()
psycopg2.InterfaceError: connection already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/sqlfluff/cli/commands.py", line 674, in fix
    result = lnt.lint_paths(
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 974, in lint_paths
    self.lint_path(
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 926, in lint_path
    for i, linted_file in enumerate(runner.run(fnames, fix), start=1):
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/sqlfluff/core/linter/runner.py", line 101, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/sqlfluff/core/linter/runner.py", line 54, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/sqlfluff/core/linter/runner.py", line 43, in iter_rendered
    yield fname, self.linter.render_file(fname, self.config)
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 652, in render_file
    return self.render_string(raw_file, fname, config, encoding)
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/sqlfluff/core/linter/linter.py", line 629, in render_string
    templated_file, templater_violations = self.templater.process(
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/sqlfluff_templater_dbt/templater.py", line 331, in process
    processed_result = self._unsafe_process(fname_absolute_path, in_str, config)
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/sqlfluff_templater_dbt/templater.py", line 457, in _unsafe_process
    node = self.dbt_compiler.compile_node(
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/dbt/compilation.py", line 550, in compile_node
    node = self._compile_node(node, manifest, extra_context)
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/dbt/compilation.py", line 388, in _compile_node
    compiled_node.compiled_sql = jinja.get_rendered(
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/dbt/clients/jinja.py", line 597, in get_rendered
    return render_template(template, ctx, node)
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/dbt/clients/jinja.py", line 548, in render_template
    return template.render(ctx)
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 12, in top-level template code
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/dbt/clients/jinja.py", line 332, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/dbt/clients/jinja.py", line 259, in call_macro
    return macro(*args, **kwargs)
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 10, in template
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/dbt/adapters/base/impl.py", line 225, in execute
    return self.connections.execute(
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/dbt/adapters/sql/connections.py", line 127, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/dbt/adapters/sql/connections.py", line 61, in add_query
    self.begin()
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/dbt/adapters/sql/connections.py", line 148, in begin
    self.add_begin_query()
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/dbt/adapters/sql/connections.py", line 136, in add_begin_query
    return self.add_query('BEGIN', auto_begin=False)
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/dbt/adapters/sql/connections.py", line 83, in add_query
    return connection, cursor
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/janbenisek/opt/anaconda3/envs/genenv/lib/python3.8/site-packages/dbt/adapters/postgres/connections.py", line 82, in exception_handler
    raise dbt.exceptions.RuntimeException(e) from e
dbt.exceptions.RuntimeException: Runtime Error
  connection already closed
```

## Steps to Reproduce
This is a dbt project using `dbt` templater

## Version
sqlfluff, version 0.9.1
Python 3.8.12
dbt: 1.0.1
Plugins:
  - redshift: 1.0.0
  - postgres: 1.0.1

## Configuration
```
[sqlfluff:core]
templater = dbt
sql_file_exts = .sql
exclude_rules = L011, L031, L042

[sqlfluff:templater:dbt]
project_dir = foo/
profile = bar

[sqlfluff:indentation]
indented_joins = false
indented_using_on = true
template_blocks_indent = false
indent_unit = tab

[sqlfluff:templater]
unwrap_wrapped_queries = true

[sqlfluff:rules]
tab_space_size = 4
max_line_length = 80
ignore_comment_lines = false
indent_unit = tab
comma_style = trailing

[sqlfluff:rules:L010]
capitalisation_policy = lower

[sqlfluff:rules:L014]
extended_capitalisation_policy = lower
unquoted_identifiers_policy = all

[sqlfluff:rules:L028]
single_table_references = consistent

[sqlfluff:rules:L029]
unquoted_identifiers_policy = aliases
quoted_identifiers_policy = aliases

[sqlfluff:rules:L030]
capitalisation_policy = lower

[sqlfluff:rules:L040]
capitalisation_policy = lower

```

**Comment by jpy-git** [comment] 2022-01-13 15:34
Hi @jan-benisek, this looks like a duplicate of #2297 so will close this in favour of that issue

**Comment by jpy-git** [comment] 2022-01-13 15:36
Since it fails on a specific file, could you share on the other issue what is different in that file vs the others. #2297 and #2140 seem to suggest it's the presence of `dbt-utils` macros?

**Closed by jpy-git** 2022-01-13 15:37 UTC
Labels: bug
