### ISSUE TITLE
Columns get shuffled and deleted

### ISSUE THREAD

**Issue by awoehrl** [sqlfluff/sqlfluff#2056] opened 2021-12-06 17:27 UTC
## Expected Behaviour
Fixing problems in a jinja-sql dbt file

```
{{ 
  config(
    materialized='snowplow_incremental',
    enabled=var('snowplow__enable_custom'),
    unique_key='event_id',
    upsert_date_key='start_tstamp',
    sort='start_tstamp',
    dist='event_id',
    partition_by = {
      "field": "start_tstamp",
      "data_type": "timestamp",
      "granularity": "day"
    },
    cluster_by=["page_view_id", "channel"]
  ) 
}}

WITH source AS (
    SELECT
        event_id
        , page_view_id
        , collector_tstamp
        , derived_tstamp
        , derived_tstamp AS start_tstamp
        , domain_userid
        , network_userid
        , NULLIF(user_id, "null") AS user_id
        , domain_sessionid
        , {{ get_marketing_channel() }}
        , mkt_medium
        , mkt_source
        , mkt_term
        , mkt_content
        , mkt_campaign
        , mkt_clickid
        , mkt_network
        , page_referrer
        , refr_urlscheme
        , refr_urlhost
        , refr_urlpath
        , refr_urlquery
        , refr_urlfragment
        , refr_medium
        , refr_source
        , refr_term
        
     FROM
        {{ ref('snowplow_web_base_events_this_run') }}
     WHERE
        --returns false if run doesn't contain new events. 
        {{ snowplow_utils.is_run_with_new_events('snowplow_web') }}
)


```

## Observed Behaviour
- columns are shuffled
- columns are removed
- dbt macro is extracted and added to the end of the file

```
{{ 
  config(
    materialized='snowplow_incremental',
    enabled=var('snowplow__enable_custom'),
    unique_key='event_id',
    upsert_date_key='start_tstamp',
    sort='start_tstamp',
    dist='event_id',
    partition_by = {
      "field": "start_tstamp",
      "data_type": "timestamp",
      "granularity": "day"
    },
    cluster_by=["page_view_id", "channel"]
  ) 
}}

WITH source AS (
    SELECT
        event_id
        , page_view_id
        , collector_tstamp
        , derived_tstamp
        , derived_tstamp AS start_tstamp
        , domain_userid
        , network_userid
        , domain_sessionid
        , mkt_medium
        {{ get_marketing_channel() }}
        , mkt_term
        , mkt_content
        , mkt_campaign
        , mkt_clickid
        , mkt_network
        , page_referrer
        , refr_urlscheme
        , refr_urlhost
        , refr_urlpath
        , refr_urlquery
        , refr_urlfragment
        , refr_medium
        , refr_source
        , refr_term
        , NULLIF(user_id, "null") AS user_id
        , (
            CASE
                -- direct
                WHEN refr_medium IS NULL
                    AND page_url NOT LIKE '%utm_%' THEN 'direct'
                WHEN refr_medium LIKE '%unknown%'
                    AND refr_source IS NULL
                    AND mkt_network IS NULL
                    AND mkt_medium IS NULL THEN 'direct'
                WHEN refr_medium IS NULL
                    AND refr_source IS NULL
                    AND mkt_network IS NULL
                    AND mkt_medium IS NULL THEN 'direct'
                WHEN refr_medium = "direct"
                    AND mkt_network IS NULL
                    AND mkt_medium IS NULL THEN 'direct'
                WHEN refr_medium = "direct"
                    AND mkt_network IS NULL
                    AND mkt_medium IS NULL THEN 'direct'
                WHEN refr_medium = 'search'
                    AND (
                        REGEXP_CONTAINS(LOWER(mkt_medium), '%(cpc|ppc|sem|paidsearch)%')
                        OR REGEXP_CONTAINS(LOWER(mkt_source), '%(cpc|ppc|sem|paidsearch)%')
                    ) THEN 'paidsearch'
                WHEN LOWER(
                    mkt_medium
                ) LIKE '%paidsearch%'
                OR LOWER(
                    mkt_source
                ) LIKE '%paidsearch%' THEN 'paidsearch'
                WHEN REGEXP_CONTAINS(LOWER(mkt_source), '%(adwords|google_paid|googleads)%')
                    OR REGEXP_CONTAINS(LOWER(mkt_medium), '%(adwords|google_paid|googleads)%') THEN 'paidsearch'
                WHEN LOWER(
                    mkt_source
                ) LIKE '%google%'
                AND LOWER(
                    mkt_medium
                ) LIKE '%ads%' THEN 'paidsearch'
                WHEN refr_urlhost IN (
                    'www.googleadservices.com'
, 'googleads.g.doubleclick.net'
                ) THEN 'paidsearch'
                WHEN REGEXP_CONTAINS(LOWER(mkt_medium), '%(cpv|cpa|cpp|content-text|advertising|ads)%') THEN 'advertising'
                WHEN REGEXP_CONTAINS(LOWER(mkt_medium), '%(display|cpm|banner)%') THEN 'display' -- organic_search
                WHEN (LOWER(refr_medium) = 'search'
                    AND mkt_medium IS NULL)
                    OR (LOWER(refr_medium) = 'search'
                        AND LOWER(mkt_medium) = 'organic') THEN 'organic_search' -- social
                WHEN refr_medium = 'social'
                    OR REGEXP_CONTAINS(LOWER(mkt_source), '^((.*(facebook|linkedin|instagram|insta|slideshare|social|tweet|twitter|youtube|lnkd|pinterest|googleplus|instagram|plus.google.com|quora|reddit|t.co|twitch|viadeo|xing|youtube).*)|(yt|fb|li))$')
                    OR REGEXP_CONTAINS(LOWER(mkt_medium), '^(.*)(social|facebook|linkedin|twitter|instagram|tweet)(.*)$') THEN 'social' -- email
                WHEN refr_medium = 'email'
                    OR LOWER(
                        mkt_medium
                    ) LIKE '_mail' THEN 'email' -- push
                WHEN mkt_medium IN (
                    'push-notification'
, 'push'
, 'Push'
                ) THEN 'push' -- affiliate
                WHEN LOWER(
                    mkt_medium
                ) LIKE 'affiliate' THEN 'affiliate' -- referral
                WHEN refr_medium = 'unknown'
                    OR LOWER(
                        mkt_medium
                    ) LIKE 'referral'
                    OR LOWER(
                        mkt_medium
                    ) LIKE 'referal' THEN 'referral'
                WHEN refr_medium = 'internal' THEN 'internal'
                ELSE 'other'
            END
        ) AS channel
    , FROM
        {{ ref('snowplow_web_base_events_this_run') }}
    WHERE
        --returns false if run doesn't contain new events. 
        {{ snowplow_utils.is_run_with_new_events('snowplow_web') }}
)
```

## Steps to Reproduce
Using a sqlfluff fix on the first sql statement on top should trigger some of the problems.

## Dialect
bigquery, dbt

## Version
0.8.2

## Configuration
```
[sqlfluff]
templater = dbt
dialect = bigquery

[sqlfluff:rules:L019]
comma_style = leading

[sqlfluff:templater:dbt]
project_dir = C:\Users\user\projects\SQL\mz-data

```

**Comment by barrywhart** [comment] 2021-12-06 23:00
I'm trying to reproduce the issue, and I'm getting an error about an undefined macro `get_marketing_channel`. Do I need any other configuration or plugins installed in order to produce the issue?
```
(sqlfluff-3.9.8) barry@barry-Inspiron-660s:~/dev/my-dbt$ sqlfluff lint models/issue_2056.sql 
=== [dbt templater] Sorting Nodes...
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
== [models/issue_2056.sql] FAIL
L:   0 | P:   0 |  TMP | dbt compilation error on file 'models/issue_2056.sql',
                       | 'get_marketing_channel' is undefined
All Finished 📜 🎉!
```

**Comment by awoehrl** [comment] 2021-12-07 08:28
Ah yes, this is a custom macro. I didn't exactly think about how SQLFluff does the linting, but of course it makes sense that it has to unpack everything first.

The example above is a custom sql built on top of the Snowplow DBT package (https://hub.getdbt.com/snowplow/snowplow_web/latest/)

## Custom macro

```
{% macro get_marketing_channel(
        mkt_medium = "mkt_medium",
        mkt_source = "mkt_source",
        mkt_network = "mkt_network",
        refr_medium = "refr_medium",
        refr_source = "refr_source",
        refr_urlhost = "refr_urlhost",
        page_url = "page_url"
    ) %}
    (
        CASE
            -- direct
            WHEN {{ refr_medium }} IS NULL
            AND {{ page_url }} NOT LIKE '%utm_%' THEN 'direct'
            WHEN {{ refr_medium }} LIKE '%unknown%'
            AND {{ refr_source }} IS NULL
            AND {{ mkt_network }} IS NULL
            AND {{ mkt_medium }} IS NULL THEN 'direct'
            WHEN {{ refr_medium }} IS NULL
            AND {{ refr_source }} IS NULL
            AND {{ mkt_network }} IS NULL
            AND {{ mkt_medium }} IS NULL THEN 'direct'
            WHEN {{ refr_medium }} = "direct"
            AND {{ mkt_network }} IS NULL
            AND {{ mkt_medium }} IS NULL THEN 'direct'
            WHEN {{ refr_medium }} = "direct"
            AND {{ mkt_network }} IS NULL
            AND {{ mkt_medium }} IS NULL THEN 'direct'
            WHEN {{ refr_medium }} = 'search'
            AND (
                regexp_contains(LOWER({{ mkt_medium }}), '%(cpc|ppc|sem|paidsearch)%')
                OR regexp_contains(LOWER({{ mkt_source }}), '%(cpc|ppc|sem|paidsearch)%')
            ) THEN 'paidsearch'
            WHEN LOWER(
                {{ mkt_medium }}
            ) LIKE '%paidsearch%'
            OR LOWER(
                {{ mkt_source }}
            ) LIKE '%paidsearch%' THEN 'paidsearch'
            WHEN regexp_contains(LOWER({{ mkt_source }}), '%(adwords|google_paid|googleads)%')
            OR regexp_contains(LOWER({{ mkt_medium }}), '%(adwords|google_paid|googleads)%') THEN 'paidsearch'
            WHEN LOWER(
                {{ mkt_source }}
            ) LIKE '%google%'
            AND LOWER(
                {{ mkt_medium }}
            ) LIKE '%ads%' THEN 'paidsearch'
            WHEN {{ refr_urlhost }} IN (
                'www.googleadservices.com',
                'googleads.g.doubleclick.net'
            ) THEN 'paidsearch'
            WHEN regexp_contains(LOWER({{ mkt_medium }}), '%(cpv|cpa|cpp|content-text|advertising|ads)%') THEN 'advertising'
            WHEN regexp_contains(LOWER({{ mkt_medium }}), '%(display|cpm|banner)%') THEN 'display' -- organic_search
            WHEN (LOWER({{ refr_medium }}) = 'search'
            AND {{ mkt_medium }} IS NULL)
            OR (LOWER({{ refr_medium }}) = 'search'
            AND LOWER({{ mkt_medium }}) = 'organic') THEN 'organic_search' -- social
            WHEN {{ refr_medium }} = 'social'
            OR regexp_contains(LOWER({{ mkt_source }}), '^((.*(facebook|linkedin|instagram|insta|slideshare|social|tweet|twitter|youtube|lnkd|pinterest|googleplus|instagram|plus.google.com|quora|reddit|t.co|twitch|viadeo|xing|youtube).*)|(yt|fb|li))$')
            OR regexp_contains(LOWER({{ mkt_medium }}), '^(.*)(social|facebook|linkedin|twitter|instagram|tweet)(.*)$') THEN 'social' -- email
            WHEN {{ refr_medium }} = 'email'
            OR LOWER(
                {{ mkt_medium }}
            ) LIKE '_mail' THEN 'email' -- push
            WHEN {{ mkt_medium }} IN (
                'push-notification',
                'push',
                'Push'
            ) THEN 'push' -- affiliate
            WHEN LOWER(
                {{ mkt_medium }}
            ) LIKE 'affiliate' THEN 'affiliate' -- referral
            WHEN {{ refr_medium }} = 'unknown'
            OR LOWER(
                {{ mkt_medium }}
            ) LIKE 'referral'
            OR LOWER(
                {{ mkt_medium }}
            ) LIKE 'referal' THEN 'referral'
            WHEN {{ refr_medium }} = 'internal' THEN 'internal'
            ELSE 'other'
        END
    ) AS channel
{% endmacro %}

```

## Linter output

```
=== [dbt templater] Sorting Nodes...
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
== [models\staging\snowplow\contexts\channels.sql] FAIL
L:  29 | P:   9 | L019 | Found trailing comma. Expected only leading.
L:  46 | P:   1 | L001 | Unnecessary trailing whitespace.
L:  47 | P:   6 | L003 | Indentation not consistent with line #4
L:  49 | P:   6 | L003 | Indentation not consistent with line #4
```

**Comment by jpy-git** [comment] 2021-12-07 11:04
seems like #1952 is a similar issue.

**Comment by barrywhart** [comment] 2021-12-08 03:46
@awoehrl: I'm trying to reproduce this issue, but I think there's some missing configuration. I get the following error (see below). Can you tell me what I'm missing, or perhaps (this would be better) provide a zip file with a complete example for reproducing the problem, including all config files, macros, sources, etc.?

```
app@1a01a52ad2f7:~/src/my-dbt$ sqlfluff lint models/issue_2056.sql 
=== [dbt templater] Sorting Nodes...
jsonschema.exceptions.ValidationError: None is not of type 'boolean'

Failed validating 'type' in schema['properties']['enabled']:
    {'default': True, 'type': 'boolean'}

On instance['enabled']:
    None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.7.9/envs/sqlfluff-3.7.9/lib/python3.7/site-packages/dbt/parser/base.py", line 381, in render_update
    self.update_parsed_node(node, config)
  File "/usr/local/pyenv/versions/3.7.9/envs/sqlfluff-3.7.9/lib/python3.7/site-packages/dbt/parser/base.py", line 324, in update_parsed_node
    config_dict = config.build_config_dict()
  File "/usr/local/pyenv/versions/3.7.9/envs/sqlfluff-3.7.9/lib/python3.7/site-packages/dbt/context/context_config.py", line 275, in build_config_dict
    base=base,
  File "/usr/local/pyenv/versions/3.7.9/envs/sqlfluff-3.7.9/lib/python3.7/site-packages/dbt/context/context_config.py", line 198, in calculate_node_config_dict
    finalized = config.finalize_and_validate()
  File "/usr/local/pyenv/versions/3.7.9/envs/sqlfluff-3.7.9/lib/python3.7/site-packages/dbt/contracts/graph/model_config.py", line 330, in finalize_and_validate
    self.validate(dct)
  File "/usr/local/pyenv/versions/3.7.9/envs/sqlfluff-3.7.9/lib/python3.7/site-packages/hologram/__init__.py", line 989, in validate
    raise ValidationError.create_from(error) from error
hologram.ValidationError: None is not of type 'boolean'

Failed validating 'type' in schema['properties']['enabled']:
    {'default': True, 'type': 'boolean'}

On instance['enabled']:
    None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/pyenv/versions/sqlfluff-3.7.9/bin/sqlfluff", line 11, in <module>
    load_entry_point('sqlfluff', 'console_scripts', 'sqlfluff')()
  File "/usr/local/pyenv/versions/3.7.9/envs/sqlfluff-3.7.9/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/pyenv/versions/3.7.9/envs/sqlfluff-3.7.9/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/pyenv/versions/3.7.9/envs/sqlfluff-3.7.9/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/pyenv/versions/3.7.9/envs/sqlfluff-3.7.9/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/pyenv/versions/3.7.9/envs/sqlfluff-3.7.9/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/app/src/src/sqlfluff/cli/commands.py", line 468, in lint
    processes=processes,
  File "/opt/app/src/src/sqlfluff/core/linter/linter.py", line 969, in lint_paths
    processes=processes,
  File "/opt/app/src/src/sqlfluff/core/linter/linter.py", line 916, in lint_path
    for i, linted_file in enumerate(runner.run(fnames, fix), start=1):
  File "/opt/app/src/src/sqlfluff/core/linter/runner.py", line 101, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/opt/app/src/src/sqlfluff/core/linter/runner.py", line 54, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/opt/app/src/src/sqlfluff/core/linter/runner.py", line 41, in iter_rendered
    fnames, config=self.config, formatter=self.linter.formatter
  File "/opt/app/src/plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py", line 256, in sequence_files
    for key, node in self.dbt_manifest.nodes.items():
  File "/usr/local/pyenv/versions/3.7.9/envs/sqlfluff-3.7.9/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/opt/app/src/plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py", line 133, in dbt_manifest
    self.dbt_config, dbt_macros_manifest, macro_hook=identity
  File "/usr/local/pyenv/versions/3.7.9/envs/sqlfluff-3.7.9/lib/python3.7/site-packages/dbt/parser/manifest.py", line 862, in load_manifest
    return ManifestLoader.load_all(config, macro_manifest, macro_hook)
  File "/usr/local/pyenv/versions/3.7.9/envs/sqlfluff-3.7.9/lib/python3.7/site-packages/dbt/parser/manifest.py", line 442, in load_all
    loader.load(macro_manifest=macro_manifest)
  File "/usr/local/pyenv/versions/3.7.9/envs/sqlfluff-3.7.9/lib/python3.7/site-packages/dbt/parser/manifest.py", line 290, in load
    self.parse_project(project, macro_manifest, old_results)
  File "/usr/local/pyenv/versions/3.7.9/envs/sqlfluff-3.7.9/lib/python3.7/site-packages/dbt/parser/manifest.py", line 237, in parse_project
    self.parse_with_cache(path, parser, old_results)
  File "/usr/local/pyenv/versions/3.7.9/envs/sqlfluff-3.7.9/lib/python3.7/site-packages/dbt/parser/manifest.py", line 188, in parse_with_cache
    parser.parse_file(block)
  File "/usr/local/pyenv/versions/3.7.9/envs/sqlfluff-3.7.9/lib/python3.7/site-packages/dbt/parser/base.py", line 432, in parse_file
    self.parse_node(file_block)
  File "/usr/local/pyenv/versions/3.7.9/envs/sqlfluff-3.7.9/lib/python3.7/site-packages/dbt/parser/base.py", line 405, in parse_node
    self.render_update(node, config)
  File "/usr/local/pyenv/versions/3.7.9/envs/sqlfluff-3.7.9/lib/python3.7/site-packages/dbt/parser/base.py", line 385, in render_update
    raise CompilationException(msg, node=node) from exc
dbt.exceptions.CompilationException: Compilation Error in model issue_2056 (models/issue_2056.sql)
  at path ['enabled']: None is not of type 'boolean'
```

**Comment by barrywhart** [comment] 2022-01-04 02:04
Looks like a duplicate of #2117, which was fixed today.

**Closed by barrywhart** 2022-01-04 02:04 UTC
Labels: bug, awaiting feedback
