### ISSUE TITLE
Trailing comma config removes the comma when using jinja template in WITH clause

### ISSUE THREAD

**Issue by rahulnbhandari** [sqlfluff/sqlfluff#1085] opened 2021-05-20 22:23 UTC
Trailing comma config removes the comma when using jinja template suing WITH clause
There is an additonal minor issue with space getting removed after **AS** and before jinja template bracket `{{`

Example sql before sqlfuff -fix

```
WITH effective_l_random AS {{
    get_effective_entity(
        "links",
        "l_random",
        "source",
        "lsat_random"
    ),
}},
cte_lsat_iri_f3_product AS {{
	get_versioned_satellite_by_exec_date(
        "source",
        "lsat_random_sat",
        ['hkey_l_random']
    ),
}}
```

changes to after sqlfuff -fix 
```
WITH effective_l_random AS{{
    get_effective_entity(
        "links",
        "l_random",
        "source",
        "lsat_random"
    ),
}}
cte_lsat_iri_f3_product AS{{
	get_versioned_satellite_by_exec_date(
        "source",
        "lsat_random_sat",
        ['hkey_l_random']
    ),
}}
```

## Expected Behaviour
```
WITH effective_l_random AS {{
    get_effective_entity(
        "links",
        "l_random",
        "source",
        "lsat_random"
    ),
}},
cte_lsat_iri_f3_product AS {{
	get_versioned_satellite_by_exec_date(
        "source",
        "lsat_random_sat",
        ['hkey_l_random']
    ),
}}
```
## Observed Behaviour
```
WITH effective_l_random AS{{
    get_effective_entity(
        "links",
        "l_random",
        "source",
        "lsat_random"
    ),
}}
cte_lsat_iri_f3_product AS{{
	get_versioned_satellite_by_exec_date(
        "source",
        "lsat_random_sat",
        ['hkey_l_random']
    ),
}}
```

## Version
Python version 3.7.6
SQLfluff version 0.5.6

## Configuration
```
# For SQLFluff Rules reference, see:
# https://docs.sqlfluff.com/en/stable/rules.html#rules-reference
[sqlfluff]
verbose = 0
nocolor = False
dialect = snowflake
templater = dbt
rules = None
exclude_rules = L034,L031,L005,L042
recurse = 0
output_line_length = 120
runaway_limit = 10
ignore = parsing
ignore_templated_areas = True

[sqlfluff:indentation]
indented_joins = False
template_blocks_indent = True

# Some rules can be configured directly from the config common to other rules.
[sqlfluff:rules]
tab_space_size = 4
max_line_length = 125
indent_unit = space
comma_style = trailing
allow_scalar = False
single_table_references = consistent
only_aliases = True

# Some rules have their own specific config.
# All SQLFluff rules can be found at: https://docs.sqlfluff.com/en/stable/rules.html#rules-reference
# When a rule in not listed below, we inherit the default behavior from above.
[sqlfluff:rules:L003]
lint_templated_tokens = True

[sqlfluff:rules:L010]  # Keywords
capitalisation_policy = upper

[sqlfluff:rules:L014]  # Unquoted identifiers
capitalisation_policy = upper

[sqlfluff:rules:L016]
# Setting to True allows us to copy/paste long URLs as comments
ignore_comment_lines = True

[sqlfluff:rules:L019]
# Leading/Trailing comma enforcement.
comma_style = trailing

[sqlfluff:rules:L030]  # Function names
capitalisation_policy = lower

[sqlfluff:rules:L038]
select_clause_trailing_comma = forbid

[sqlfluff:rules:L040]  # Null & Boolean Literals
capitalisation_policy = capitalise
```

**Comment by barrywhart** [comment] 2021-07-31 18:44
Note: The description mentions Jinja, but the `.sqlfluff` file provided specifies dbt.

**Comment by barrywhart** [comment] 2021-07-31 20:18
I'd be happy to look at this one if someone can provide a Jinja (not dbt) test case.

**Comment by rahulnbhandari** [comment] 2021-07-31 21:41
The issue with sql in dbt project having jinja

**Comment by rahulnbhandari** [comment] 2021-08-02 03:57
Macros in `{{}}` in above example

**Comment by barrywhart** [comment] 2021-09-25 01:21
This issue looks similar to #1162, #1425, and #1438, so I think it may be addressed by these two PRs:
* #1431
* #1443 

Test again after 0.6.7 or higher is released.

**Comment by barrywhart** [comment] 2021-10-02 20:08
@rahulnbhandari: I am unable to test and reproduce this issue because I don't have a `get_effective_entity` macro. Can you please provide a complete example for reproducing the issue?

```
Encountered an error:
Runtime Error
  Compilation Error in model issue_1085 (models/example/issue_1085.sql)
    'get_effective_entity' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
```

**Closed** 2021-10-31 22:59 UTC
Labels: bug, dbt, jinja, awaiting feedback
