### ISSUE TITLE
dbt templater does not work with dbt 1.0.0

### ISSUE THREAD

**Issue by tekumara** [sqlfluff/sqlfluff#2068] opened 2021-12-08 02:54 UTC
## Observed Behaviour
```
Traceback (most recent call last):
  File "/Users/tekumara/jaffleshop/.venv/bin/sqlfluff", line 5, in <module>
    from sqlfluff.cli.commands import cli
  File "/Users/tekumara/jaffleshop/.venv/lib/python3.9/site-packages/sqlfluff/__init__.py", line 6, in <module>
    from sqlfluff.api import lint, fix, parse, list_rules, list_dialects  # noqa: F401
  File "/Users/tekumara/jaffleshop/.venv/lib/python3.9/site-packages/sqlfluff/api/__init__.py", line 6, in <module>
    from sqlfluff.api.simple import lint, fix, parse, APIParsingError
  File "/Users/tekumara/jaffleshop/.venv/lib/python3.9/site-packages/sqlfluff/api/simple.py", line 3, in <module>
    from sqlfluff.core import Linter
  File "/Users/tekumara/jaffleshop/.venv/lib/python3.9/site-packages/sqlfluff/core/__init__.py", line 10, in <module>
    from sqlfluff.core.linter import Linter
  File "/Users/tekumara/jaffleshop/.venv/lib/python3.9/site-packages/sqlfluff/core/linter/__init__.py", line 8, in <module>
    from sqlfluff.core.linter.linter import Linter
  File "/Users/tekumara/jaffleshop/.venv/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 32, in <module>
    from sqlfluff.core.rules import get_ruleset
  File "/Users/tekumara/jaffleshop/.venv/lib/python3.9/site-packages/sqlfluff/core/rules/__init__.py", line 12, in <module>
    for plugin_rules in get_plugin_manager().hook.get_rules():
  File "/Users/tekumara/jaffleshop/.venv/lib/python3.9/site-packages/sqlfluff/core/plugin/host.py", line 12, in get_plugin_manager
    pm.load_setuptools_entrypoints(project_name)
  File "/Users/tekumara/jaffleshop/.venv/lib/python3.9/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/Users/oliver.mannion/.pyenv/versions/3.9.7/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/oliver.mannion/.pyenv/versions/3.9.7/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/tekumara/jaffleshop/.venv/lib/python3.9/site-packages/sqlfluff_templater_dbt/__init__.py", line 3, in <module>
    from sqlfluff_templater_dbt.templater import DbtTemplater
  File "/Users/tekumara/jaffleshop/.venv/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 14, in <module>
    from dbt.config.profile import PROFILES_DIR
ImportError: cannot import name 'PROFILES_DIR' from 'dbt.config.profile' (/Users/tekumara/jaffleshop/.venv/lib/python3.9/site-packages/dbt/config/profile.py)
```
## Version
sqlfluff 0.8.2
dbt 1.0.0

## Configuration
```
[tool.sqlfluff.core]
templater = "dbt"
sql_file_exts = ".sql,.sql.j2,.dml,.ddl"
dialect = "snowflake"

[tool.sqlfluff.templater.dbt]
project_dir = "."
profile = "snowflake"
```

**Comment by tekumara** [comment] 2021-12-08 02:56
I think it is now `DEFAULT_PROFILES_DIR` in dbt 1.0.0

**Comment by jpy-git** [comment] 2021-12-08 10:29
@tekumara closing as it's a duplicate of #2048

**Closed by jpy-git** 2021-12-08 10:29 UTC
Labels: bug
