### ISSUE TITLE
Unrecoverable failure in Jinja templating: 'dbt_utils' is undefined

### ISSUE THREAD

**Issue by tjwaterman99** [sqlfluff/sqlfluff#710] opened 2021-01-24 04:31 UTC
I'm trying to run sqlfluff on a dbt model:

```
{{ config(materialized='view') }}

select
    {{ dbt_utils.hash("message_id") }},
    *
from user_session_events
```

But I received the following error:

```
L:   - | P:   - |  TMP | Unrecoverable failure in Jinja templating: 'dbt_utils'
                       | is undefined. Have you configured your variables?
                       | https://docs.sqlfluff.com/en/latest/configuration.html
L:   4 | P:   8 |  TMP | Undefined jinja template variable: 'dbt_utils'
```

I've found the section about [updating the Jinja templator](https://docs.sqlfluff.com/en/stable/configuration.html#macro-templating) by using `load_macros_from_path` in the `.sqlfluff` file.

So I tried updating my config file by adding the install location of `dbt_util`'s macros directory:

```
[sqlfluff:templater:jinja]
apply_dbt_builtins = True
load_macros_from_path=./dbt_modules/dbt_utils/macros
```

But now when I run `sqlfluff lint`, I receive an error saying that sqlfluff can no longer parse the `materialization` tag:

```
Traceback (most recent call last):
  File "/usr/local/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/cli/commands.py", line 172, in lint
    result = lnt.lint_paths(paths, verbosity=verbose, ignore_non_existent_files=False)
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/linter.py", line 912, in lint_paths
    ignore_non_existent_files=ignore_non_existent_files))
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/linter.py", line 898, in lint_path
    fix=fix, config=config))
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/linter.py", line 713, in lint_string
    parsed, vs, time_dict = self.parse_string(s=s, fname=fname, verbosity=verbosity, config=config)
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/linter.py", line 611, in parse_string
    s, templater_violations = self.templater.process(s, fname=fname, config=config or self.config)
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/templaters.py", line 319, in process
    ctx.update(self._extract_macros_from_path(macros_path, env=env, ctx=live_context))
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/templaters.py", line 210, in _extract_macros_from_path
    env=env, ctx=ctx
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/templaters.py", line 200, in _extract_macros_from_path
    template, env=env, ctx=ctx
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/templaters.py", line 175, in _extract_macros_from_template
    macro_template = env.from_string(template, globals=ctx)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 53, in template
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'materialization'.
```

## Version

sqlfluff, version 0.3.6
Python 3.7.8

## Configuration

```
[sqlfluff]
dialect = snowflake

[sqlfluff:templater:jinja]
apply_dbt_builtins = True
load_macros_from_path=./dbt_modules/dbt_utils/macros
```

**Comment by NiallRees** [comment] 2021-01-24 13:04
Hi @tjwaterman99 thanks for this - I think your issue will be solved in 0.4.0 (latest pre release currently 0.4.0a3) with the addition of dbt templating. See https://docs.sqlfluff.com/en/latest/configuration.html?highlight=dbt#dbt-project-configuration for guidance and feel free to drop any questions you may have in the Slack workspace, there's an invite link in the readme if you've not joined already. Going to close this for now 🙂

**Closed by NiallRees** 2021-01-24 13:04 UTC
Labels: bug

**Comment by tjwaterman99** [comment] 2021-01-24 18:06
@NiallRees Got it, thank you! I was able to resolve that issue by trying out 0.4.0.a3.

I did still find a few others after upgrading however - I've created some reproducible examples here: https://github.com/tjwaterman99/sqfluff_dbt_errors_examples

The dbt specific ones are related to having a model that is `enabled: false`, as well as linting errors from what I _think_ is the sql that sqlfluff injects when parsing out the `dbt_utils.hash` functions. 

The lint errors related to the injected sql seem tough since I can't easily control any of the SQL in the packages themselves.

Would it be helpful if I open separate issues for each of those examples?

**Comment by tjwaterman99** [comment] 2021-01-24 18:19
I've also added a github workflow to make it easier to reproduce those:

https://github.com/tjwaterman99/sqfluff_dbt_errors_examples/runs/1757960629

**Comment by NiallRees** [comment] 2021-01-24 18:39
Yes please @tjwaterman99 issues for each would be great 🙂

**Comment by akcx** [comment] 2022-07-12 14:21
I am facing the same issue for the `dbt` builtin `var`.

I have `apply_dbt_builtins` enabled in my config.
```
[sqlfluff:templater:jinja]
apply_dbt_builtins = True
load_macros_from_path = macros
```

I get the following error on running `lint`.
```
L:   1 | P:   1 |  TMP | Unrecoverable failure in Jinja templating: 'var' is
                       | undefined. Have you configured your variables?
                       | https://docs.sqlfluff.com/en/latest/configuration.html
```

I also tried using using custom macros defined under `[sqlfluff:templater:jinja:macros]` based on instructions [on this page](https://docs.sqlfluff.com/en/stable/configuration.html#dbt-project-configuration) but it didn't work for me.

I am running `sqlfluff` version `0.11.0`.

Could anyone please help me understand what the problem is? 

Thanks!

**Comment by cal859** [comment] 2022-12-08 15:38
The same as is happening @akcx is also happening for me, but with the [run_query](https://docs.getdbt.com/reference/dbt-jinja-functions/run_query) builtin. (error message below)

```
==== parsing violations ====
L:   1 | P:   1 |  TMP | Unrecoverable failure in Jinja templating: 'run_query' is
                       | undefined. Have you configured your variables?
                       | https://docs.sqlfluff.com/en/latest/configuration.html
```

My setup is:

```
dialect = redshift
templater = dbt
```

I have the same config, but am using `sqlfluff` version `1.4.2`. I was also unable to fix by adding it as a custom macro (code below)

```
[sqlfluff:templater:jinja:macros]
run_query = {% macro run_query(query) %}'query'{% endmacro %}
```

Any ideas on the issue and/or a fix much appreciated! Please let me know if you require any more detail

**Comment by manugarri** [comment] 2023-02-16 10:56
why is this issue closed? The problem still happens. Running a jinja templater to run dbt models will fail if you use `dbt_utils`

**Comment by wyardley** [comment] 2025-01-13 19:53
Did anyone resolve this? I'm not getting "unrecoverable failure", but still getting an error even when setting `apply_dbt_builtins = True` and including `load_macros_from_path = macros,dbt_packages/dbt_utils/macros` or `load_macros_from_path = macros,dbt_packages/dbt_utils/macros/sql`. 

The code is something like:
```
with source as (
  select
    {{ dbt_utils.star(from
[...]
```

where `dbt_packages/dbt_utils/macros/sql/star.sql` is where that macro is defined, and this error is returned:
```
L:  11 | P:   8 |  TMP | Undefined jinja template variable: 'dbt_utils'
```

**Comment by neozenith** [comment] 2025-05-12 18:47
If anyone is here because of `ref()` trying to use the 2 argument form then the following worked for me:

```
dbt_ref = {% macro ref(package_or_model, model_ref=none) %}{% if model_ref %}{{model_ref}}{% else %}{{ package_or_model }}{% endif %}{% endmacro %}
```
