### ISSUE TITLE
Error: "pop from an empty set"

### ISSUE THREAD

**Issue by jamiet-msm** [sqlfluff/sqlfluff#1981] opened 2021-11-26 10:06 UTC
## Expected Behaviour

No runtime error occurs

## Observed Behaviour

Runtime error

```default
CRITICAL   [L054] Applying rule L054 threw an Exception: 'pop from an empty set' 
Traceback (most recent call last):
  File "/opt/conda/envs/py3/lib/python3.8/site-packages/sqlfluff/core/rules/base.py", line 324, in crawl
    res = self._eval(
  File "/opt/conda/envs/py3/lib/python3.8/site-packages/sqlfluff/rules/L054.py", line 112, in _eval
    column_reference_category_set.pop()
KeyError: 'pop from an empty set'
== [/dataplatform/google/runtime/modules/CommonDataModel/bigquery-views/cdm_processing.FctEnergyAppStatusUpdateProcessing.sql] FAIL
L:   7 | P:   1 | L054 | Unexpected exception: 'pop from an empty set'; Could you
                       | open an issue at
                       | https://github.com/sqlfluff/sqlfluff/issues ? You can
                       | ignore this exception for now, by adding '--noqa: L054'
                       | at the end of line 7
L:  17 | P:   1 | L054 | Unexpected exception: 'pop from an empty set'; Could you
                       | open an issue at
                       | https://github.com/sqlfluff/sqlfluff/issues ? You can
                       | ignore this exception for now, by adding '--noqa: L054'
                       | at the end of line 17
L:  27 | P:   1 | L054 | Unexpected exception: 'pop from an empty set'; Could you
                       | open an issue at
                       | https://github.com/sqlfluff/sqlfluff/issues ? You can
                       | ignore this exception for now, by adding '--noqa: L054'
                       | at the end of line 27
```

## Steps to Reproduce

Here is the content of the file referred to in the error message (cdm_processing.FctEnergyAppStatusUpdateProcessing.sql):

```sql
/* jscpd:ignore-start */
SELECT
    t.body.application.id AS ApplicationId,
    t.body.cashbackStatus.electricity.current.status AS ElectricityCashBackStatus, --noqa
    t.body.cashbackStatus.gas.current.status AS GasCashBackStatus --noqa
FROM `${datalake_project_id}.${name_prefix_sans_dashes}_event_service_presentation.applicationStatusUpdate_1_229_v2` AS t
GROUP BY  --noqa: PRS
    t.body.application.id,
    t.body.cashbackStatus.electricity.current.status, --noqa
    t.body.cashbackStatus.gas.current.status  --noqa
UNION ALL
SELECT
    t.body.application.id AS ApplicationId,
    t.body.cashbackStatus.electricity.current.status AS ElectricityCashBackStatus, --noqa
    t.body.cashbackStatus.gas.current.status AS GasCashBackStatus --noqa
FROM `${datalake_project_id}.${name_prefix_sans_dashes}_event_service_presentation.applicationStatusUpdate_3_296_v2` AS t
GROUP BY  --noqa: PRS
    t.body.application.id,
    t.body.cashbackStatus.electricity.current.status, --noqa
    t.body.cashbackStatus.gas.current.status  --noqa
UNION ALL
SELECT
    t.body.application.id AS ApplicationId,
    t.body.cashbackStatus.electricity.current.status AS ElectricityCashBackStatus, --noqa
    t.body.cashbackStatus.gas.current.status AS GasCashBackStatus --noqa
FROM `${datalake_project_id}.${name_prefix_sans_dashes}_event_service_presentation.applicationStatusUpdate_9_229_v2` AS t
GROUP BY  --noqa: PRS
    t.body.application.id,
    t.body.cashbackStatus.electricity.current.status,  --noqa
    t.body.cashbackStatus.gas.current.status   --noqa
/* jscpd:ignore-end */

```
Note that the templating used here is terraform templating (https://www.terraform.io/docs/language/functions/templatefile.html)

## Dialect
bigquery 

## Version
Include the output of `sqlfluff --version` along with your Python version

## Configuration
Not using a config file however we're doing this:

```
sqlfluff lint --dialect bigquery --exclude-rules L016,L031,L014
```

**Comment by jpy-git** [comment] 2021-11-26 13:52
@jamiet-msm @WittierDinosaur This is a parsing issue rather than the rule logic.

The rule is receiving unparsable sql (at least according to what has been added to the grammar so far). Not sure why unparsable sections get passed to the rules for evaluation, so I will investigate that. Also feels like parse errors should not be ignorable as any subsequent errors triggered by parse error are misleading.

The root cause of this issue is that this sort of syntax doesn't currently parse in bigquery grammar: `t.body.cashbackStatus.electricity.current.status`

Minimum reproducable example:
![image](https://user-images.githubusercontent.com/80432516/143590071-7167cca0-7728-4344-ada1-2719b7ee230f.png)

No issues caused if `<database>.<schema>.<table>.<col>` format received:
![image](https://user-images.githubusercontent.com/80432516/143590574-731dab95-aef1-4602-a057-ca51d03d6f95.png)

The label should be changed to bigquery and the title to add something like
"Add t.body.cashbackStatus.electricity.current.status reference syntax to bigquery grammar" (not familiar with bigquery myself so feel free to insert the proper name for that sort of syntax) 😄

**Comment by WittierDinosaur** [comment] 2021-11-26 14:08
Off the top of my head - i imagine there's a limit to the number of . in a column. Parse issues shouldn't make it through the parser - I'll look into it over the weekend

**Comment by jpy-git** [comment] 2021-11-26 14:57
amazing thanks, interestingly the parse error isn't raised for ansi.

![image](https://user-images.githubusercontent.com/80432516/143599127-0dfb0954-58cc-49ab-90db-392e6428b336.png)

**Comment by WittierDinosaur** [comment] 2021-11-26 15:00
I'm a little confused. If you run sqlfluff parse, is there an unparsable section in the parse tree?

**Comment by jpy-git** [comment] 2021-11-26 15:04
within the group by clause when using big query
![image](https://user-images.githubusercontent.com/80432516/143599790-0e1cefc5-23ad-4d0e-9da5-417d04af3093.png)

however, no parse issue for ansi
![image](https://user-images.githubusercontent.com/80432516/143599993-7edfeb96-9f6b-4ede-8b98-9e42169781c2.png)

so probably just need to recreate the column logic from ansi into big query

**Comment by jpy-git** [comment] 2021-11-26 15:09
the rule looks at groupby_clause, which has an unexpected unparsable child segment.
![image](https://user-images.githubusercontent.com/80432516/143600446-70d1fb90-c1ae-4ded-a2ac-96300ffe0716.png)

**Comment by jamiet-msm** [comment] 2021-11-26 17:51
> "Add t.body.cashbackStatus.electricity.current.status reference syntax to bigquery grammar" (not familiar with bigquery myself so feel free to insert the proper name for that sort of syntax)

Thx folks. BigQuery allows a column to contains nested data structures (might help to think of it as the column being of type JSON - although that's not what it is) hence the dot notation here is navigating through that hierarchical data structure.

![image](https://user-images.githubusercontent.com/79862277/143617076-8a5e3b0e-7288-4215-ad57-1055297d8c6b.png)

**Comment by tunetheweb** [comment] 2021-11-27 09:34
Multiple dots are handled fine in SQLFluff.

The issue is the `current` part of the objet names, changing that to `current1` allows it to parse and lint fine

`CURRENT` is a [reserved keyword in BigQuery](https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#reserved_keywords), but there is a [special opt out](https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical) that we don't handle (emphasis mine):

> A reserved keyword must be a quoted identifier if it is a standalone keyword or the first component of a path expression. _It may be unquoted as the second or later component of a path expression_.

Might have a fix for this...

**Closed** 2021-11-27 12:16 UTC
Labels: bug, rule bug

**Comment by jamiet-msm** [comment] 2021-11-27 13:11
Thank you all for the rapid response. Is it fair of me to ask when this might show up in a new tag?

**Comment by tunetheweb** [comment] 2021-11-27 13:19
That's entirely fair, but I don't have a definitive answer for you! 😁

Officially in our [README](https://github.com/sqlfluff/sqlfluff#releases), we say we release once a month and we just released 0.8.3 so could be a few weeks. Unofficially, we have so many people contributing so many great enhancements at the moment that I would expect it to be sooner than that.

**Comment by tunetheweb** [comment] 2021-11-27 13:20
Plus I'm sure no one wants to have a release just before Christmas! So might be good to get one last 2021 release out, well enough before that.

**Comment by jpy-git** [comment] 2021-11-27 13:22
I think @alanmcruickshank mentioned that we might need to make the next release a minor one due to non-backwards compatible changes we're making to tidy up the simple api (#1951). I still think there are some more additional improvements we should make to the API before then, so no need to rush 😄
