### ISSUE TITLE
sqlfluff-templater-dbt isn't compatible with dbt-core 1.4.1

### ISSUE THREAD

**Issue by kokorin** [sqlfluff/sqlfluff#4345] opened 2023-02-03 12:35 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

The following exception appears when running sqlfluff with DBT templater (using DBT > 1.4.0):
```
ImportError: cannot import name 'CompilationException' from 'dbt.exceptions'
```

DBT 1.4.0 introduced [breaking changes:](https://github.com/dbt-labs/dbt-core/releases/tag/v1.4.0)

> Breaking Changes
>
>    Relevant for maintainers of adapter plugins: Cleaned up exceptions to directly raise in code. Also updated the existing exception to meet PEP guidelines. Removed use of all exception functions in the code base and marked them all as deprecated to be removed next minor release. (https://github.com/dbt-labs/dbt-core/issues/6339, https://github.com/dbt-labs/dbt-core/issues/6393, https://github.com/dbt-labs/dbt-core/issues/6460)

### Expected Behaviour

Runs without exceptions

### Observed Behaviour

Exception appears

### How to reproduce

Just install latests sqlfluff-templater-dbt  and dbt-core

### Dialect

Snowflake

### Version

```shell
sqlfluff.exe --version
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
    ...
    from sqlfluff_templater_dbt.templater import DbtTemplater
  File "...\venv\lib\site-packages\sqlfluff_templater_dbt\templater.py", line 17, in <module>
    from dbt.exceptions import (
ImportError: cannot import name 'CompilationException' from 'dbt.exceptions' (...\venv\lib\site-packages\dbt\exceptions.py)

```

sqlfluff==1.4.5
sqlfluff-templater-dbt==1.4.5
dbt-core==1.4.1
dbt-extractor==0.4.1
dbt-snowflake==1.4.0

### Configuration

```
[sqlfluff]
dialect = snowflake
templater = dbt

[sqlfluff:templater]
unwrap_wrapped_queries = 1

[sqlfluff:rules]
tab_space_size = 2

[sqlfluff:rules:L016]
max_line_length = 120
ignore_comment_lines = 1

[sqlfluff:rules:L010]
capitalisation_policy = lower
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by pdebelak** [comment] 2023-02-03 16:20
This is a duplicate of #4315 which was fixed in #4317.

**Comment by greg-finley** [comment] 2023-02-03 21:55
duplicate

**Closed by greg-finley** 2023-02-03 21:55 UTC
Labels: bug

**Comment by yaozhang09** [comment] 2023-02-03 22:06
I've tried bumping the version of sqlfluff and sqlfluff-dbt-templater to `v2.0.0a4` which introduced the fix but am still getting the same error when running sqlfluff via pre-commit hooks
<img width="1017" alt="Screenshot 2023-02-03 at 2 04 39 PM" src="https://user-images.githubusercontent.com/114429763/216719938-e48d1bf2-2537-470c-9036-8d98d7b41392.png">
