### ISSUE TITLE
dbt.exceptions.InternalException: Asked to compile <class 'dbt.contracts.graph.compiled.CompiledModelNode'> node, but it has no compiled form

### ISSUE THREAD

**Issue by dwallace0723** [sqlfluff/sqlfluff#1849] opened 2021-11-08 19:52 UTC
Looks like we're seeing identical behavior to #1518 , #1613 , and #857 after upgrading sqlfluff to version `0.7.1`. When attempting to run `sqlfluff lint` on our dbt project, we get the following exception:

```
dbt@b263229e2f53:/workspaces/dbt-dutchie$ sqlfluff lint models/shared/dispensaries.sql models/shared/intermediate/int__dispensaries.sql  --nofail
=== [dbt templater] Sorting Nodes...
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
=== [dbt templater] Sorting Nodes...
Traceback (most recent call last):
  File "/opt/venv/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/sqlfluff/cli/commands.py", line 389, in lint
    result = lnt.lint_paths(
  File "/opt/venv/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 851, in lint_paths
    self.lint_path(
  File "/opt/venv/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 825, in lint_path
    for linted_file in runner.run(fnames, fix):
  File "/opt/venv/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 95, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/opt/venv/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 48, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/opt/venv/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 41, in iter_rendered
    yield fname, self.linter.render_file(fname, self.config)
  File "/opt/venv/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 576, in render_file
    return self.render_string(raw_file, fname, config, encoding)
  File "/opt/venv/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 553, in render_string
    templated_file, templater_violations = self.templater.process(
  File "/opt/venv/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 308, in process
    processed_result = self._unsafe_process(fname_absolute_path, in_str, config)
  File "/opt/venv/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 377, in _unsafe_process
    node = self.dbt_compiler.compile_node(
  File "/opt/venv/lib/python3.9/site-packages/dbt/compilation.py", line 543, in compile_node
    node = self._compile_node(node, manifest, extra_context)
  File "/opt/venv/lib/python3.9/site-packages/dbt/compilation.py", line 377, in _compile_node
    compiled_node = _compiled_type_for(node).from_dict(data)
  File "/opt/venv/lib/python3.9/site-packages/dbt/compilation.py", line 39, in _compiled_type_for
    raise InternalException(
dbt.exceptions.InternalException: Asked to compile <class 'dbt.contracts.graph.compiled.CompiledModelNode'> node, but it has no compiled form
```

## Expected Behaviour
No exceptions.

## Observed Behaviour

```
dbt@b263229e2f53:/workspaces/dbt-dutchie$ sqlfluff lint models/shared/dispensaries.sql models/shared/intermediate/int__dispensaries.sql  --nofail
=== [dbt templater] Sorting Nodes...
=== [dbt templater] Compiling dbt project...
=== [dbt templater] Project Compiled.
=== [dbt templater] Sorting Nodes...
Traceback (most recent call last):
  File "/opt/venv/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/sqlfluff/cli/commands.py", line 389, in lint
    result = lnt.lint_paths(
  File "/opt/venv/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 851, in lint_paths
    self.lint_path(
  File "/opt/venv/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 825, in lint_path
    for linted_file in runner.run(fnames, fix):
  File "/opt/venv/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 95, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/opt/venv/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 48, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/opt/venv/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 41, in iter_rendered
    yield fname, self.linter.render_file(fname, self.config)
  File "/opt/venv/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 576, in render_file
    return self.render_string(raw_file, fname, config, encoding)
  File "/opt/venv/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 553, in render_string
    templated_file, templater_violations = self.templater.process(
  File "/opt/venv/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 308, in process
    processed_result = self._unsafe_process(fname_absolute_path, in_str, config)
  File "/opt/venv/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 377, in _unsafe_process
    node = self.dbt_compiler.compile_node(
  File "/opt/venv/lib/python3.9/site-packages/dbt/compilation.py", line 543, in compile_node
    node = self._compile_node(node, manifest, extra_context)
  File "/opt/venv/lib/python3.9/site-packages/dbt/compilation.py", line 377, in _compile_node
    compiled_node = _compiled_type_for(node).from_dict(data)
  File "/opt/venv/lib/python3.9/site-packages/dbt/compilation.py", line 39, in _compiled_type_for
    raise InternalException(
dbt.exceptions.InternalException: Asked to compile <class 'dbt.contracts.graph.compiled.CompiledModelNode'> node, but it has no compiled form
```

## Steps to Reproduce
`sqlfluff lint` any files in the dbt project.

## Dialect
`snowflake`

## Version
```
$ sqlfluff --version
sqlfluff, version 0.7.1
$ python --version
Python 3.9.7
$ poetry show sqlfluff
name         : sqlfluff
version      : 0.7.1
description  : The SQL Linter for Humans

dependencies
 - appdirs *
 - cached-property *
 - click >=7.1
 - colorama >=0.3
 - configparser *
 - diff-cover >=2.5.0
 - Jinja2 *
 - oyaml *
 - pathspec *
 - pytest *
 - tblib *
 - toml *
 - typing-extensions *
$ poetry show sqlfluff-templater-dbt
name         : sqlfluff-templater-dbt
version      : 0.7.1
description  : Lint your dbt project SQL.

dependencies
 - dbt >=0.17
 - sqlfluff >=0.7.0
```

## Configuration
```
[sqlfluff]
dialect = snowflake
templater = dbt
rules = L001,L002,L003,L004,L005,L006
ignore = parsing,templating

[sqlfluff:rules]
max_line_length = 120
comma_style = trailing

[sqlfluff:rules:L010]
capitalisation_policy = upper
```

**Comment by barrywhart** [comment] 2021-11-10 14:26
By chance, are all of your models ephemeral? That's the only explanation I can think of.

If not, can you provide an example for reproducing this issue? Specifically, we need example model files.

**Comment by dwallace0723** [comment] 2021-11-10 15:25
> By chance, are all of your models ephemeral? That's the only explanation I can think of.

@barrywhart yeah, 37% of our dbt project (~140 dbt models) are ephemeral.

**Comment by barrywhart** [comment] 2021-11-10 15:35
I was wondering if they all were. It should still work if some of them are, *unless* there is a loop somewhere, e.g. models A, B, and C are all ephemeral, and they depend on one another.

We won't be able to fix this without an example. SQLFluff definitely supports ephemeral models in some cases (see the models in [this test directory](https://github.com/sqlfluff/sqlfluff/tree/main/plugins/sqlfluff-templater-dbt/test/fixtures/dbt/dbt_project/models/depends_on_ephemeral) for the dbt templater), so there must be something different about your project.

**Comment by dwallace0723** [comment] 2021-11-10 15:40
> unless there is a loop somewhere, e.g. models A, B, and C are all ephemeral, and they depend on one another.

@barrywhart dbt doesnt allow loops, so this isn't possible.

> We won't be able to fix this without an example. SQLFluff definitely supports ephemeral models in some cases

@barrywhart here is an example of an ephemeral model it fails on:

```sql
{{ config(materialized = 'ephemeral') }}

with
	stg_users as (
		select * from {{ ref('stg_users') }}
),

dispensary_super_admins as (
    select * from {{ ref('dispensary_super_admins') }}
),

account_executive as (
    select
        *
    from
        dispensary_super_admins
    where
        role = 'AccountExecutive'
),

account_manager_primary as (
    select
        *
    from
        dispensary_super_admins
    where
        role = 'AccountManagerPrimary'
),

account_manager_secondary as (
    select
        *
    from
        dispensary_super_admins
    where
        role = 'AccountManagerSecondary'
),

customer_success_manager as (
    select
        *
    from
        dispensary_super_admins
    where
        role = 'CustomerSuccessManager'
),

int__dispensary_integrations as (
    select * from {{ ref('int__dispensary_integrations') }}
),

pos_integrations as (
    select
        *
    from
        int__dispensary_integrations
    where
        integration_category = 'pos'
),

fleet_management_integrations as (
    select
        *
    from
        int__dispensary_integrations
    where
        integration_category = 'fleetManagement'
),

payments_integrations as (
    select
        *
    from
        int__dispensary_integrations
    where
        integration_category = 'payments'
),

int__dispensary_list_integrations as (
    select * from {{ ref('int__dispensary_list_integrations') }}
),

int__dispensary_device_summary as (
    select * from {{ ref('int__dispensary_device_summary') }}
),

int__dispensaries_with_valid_specials as (
    select * from {{ ref('int__dispensaries_with_valid_specials') }}
),

paused_dispensaries as (
    select
        dispensary_id,
        max(paused_at) as paused_at
    from
        {{ ref('order_suspensions') }}
    where
        is_active
    group by 1
),

final as (
    select
        _id::string as dispensary_id,
        created_at,
        updated_by,
        created_by,
        profile:name::string as name,
        profile:status::string as status,
        profile,
        profile:address::string as address,
        profile:chain::string as chain,
        profile:description::string as description,

            -- Dates

        profile:firstActiveAt::timestamp as first_active_at,
        profile:firstEmbeddedAt::timestamp as first_embedded_at,
        profile:latestEmbeddedView::timestamp as latest_embedded_at,

        profile:hideFromCCT::boolean as hide_from_cct,
        profile:menuScore::number as menu_score,

            -- Pauses
        nvl2(paused_dispensaries.dispensary_id, true, false) as is_paused,
        paused_dispensaries.paused_at,

            -- Location

        profile:location as location,
        profile:location:city::string as city,
        nvl(profile:location:country::string,
            case
            when profile:address like '%Canada%' then 'Canada'
            when profile:address like '%USA%'
                or profile:address like '%Puerto Rico%'
                or profile:address like '%, OR'
                or profile:address like '%, CA'
                then 'United States'
            end)
        as country,
        profile:location:county::string as county,
        profile:location:state::string as state,
        profile:location:zipcode::string as zipcode,
        profile:location:coordinates as coordinates,

            -- Super Admins

        account_executive.name as account_executive,
        account_manager_primary.name as account_manager_primary,
        account_manager_secondary.name as account_manager_secondary,
        customer_success_manager.name as customer_success_manager,
        case
            when customer_success_manager.name in ('Kimberly Veliz', 'Christian Mendoza', 'Austin Bellows') then 'East'
            when customer_success_manager.name in ('Nicole Caldwell', 'Michael Nelson', 'Lauren Berluti', 'Duni Disston') then 'Canada'
            when customer_success_manager.name in ('Ryan Dupuie', 'Megan Monk', 'Pablo Paez') then 'Pacific West'
            when customer_success_manager.name in ('James Jacobs', 'Liz Bruns', 'Nick Vrbenec', 'Jolie Perkins') then 'Mountain West'
            when customer_success_manager.name in ('Mia Trasolini', 'Justice Davis') then 'Enterprise'
            when customer_success_manager.name in ('The Growth Team', 'Loris Lamarque', 'Nick Hamilton', 'Abby Lal', 'Elisha Lamar') then 'The Growth Team'
        end as territory_pod,

            -- Integrations

        pos_integrations.adapter as pos_integration,
        fleet_management_integrations.adapter as fleet_management_integration,
        payments_integrations.adapter as payments_integration,
        int__dispensary_list_integrations.list_live_integrations,

            -- Devices

        case when int__dispensary_device_summary.count_linked_devices > 0 then true else false end as has_terminal,

            -- Specials

        iff(int__dispensaries_with_valid_specials.dispensary_id is not null, true, false) as has_valid_special,

            -- Store Settings

        profile:acceptsTips::boolean as accepts_tips,
        profile:cashless::boolean as is_cashless,
        profile:deliveryFee::string as delivery_fee,
        profile:deliveryMin::string as delivery_min,
        profile:featureFlags:enableAfterHoursOrdering::boolean as enable_after_hours_ordering,
        profile:featureFlags:enableArrivals::boolean as enable_arrivals,
        profile:featureFlags:enableBogoSpecials::boolean as enable_bogo_specials,
        profile:featureFlags:enableNonTerminalAutoConfirm::boolean as enable_non_terminal_autoconfirm,
        profile:feeTiers as fee_tiers,
        profile:kioskOrderingEnabled::boolean as kiosk_ordering_enabled,
        profile:kioskConfig:directedOrders::boolean as kiosk_directed_orders,
        profile:kioskConfig:fullNameOnly::boolean as kiosk_full_name_only,
        profile:kioskConfig:hideEmailField::boolean as kiosk_hide_email_field,
        profile:kioskConfig:hidePhoneField::boolean as kiosk_hide_phone_field,
        profile:kioskConfig:notesField::boolean as kiosk_notes_field,
        profile:kioskConfig:phoneRequired::boolean as kiosk_phone_required,
        profile:kioskConfig:showBirthdateField::boolean as kiosk_show_birthdate_field,
        profile:menuOrder::string as menu_order,
        profile:ordersConfig:autoConfirm::boolean as order_autoconfirm,
        profile:orderTypesConfig:curbsidePickup:enableASAPOrdering::boolean as enable_curbside_asap_ordering,
        profile:orderTypesConfig:curbsidePickup:enableScheduledOrdering::boolean as enable_curbside_scheduled_ordering,
        profile:orderTypesConfig:delivery:enableASAPOrdering::boolean as enable_delivery_asap_ordering,
        profile:orderTypesConfig:delivery:enableScheduledOrdering::boolean as enable_delivery_scheduled_ordering,
        profile:orderTypesConfig:driveThruPickup:enableASAPOrdering::boolean as enable_drive_thru_pickup_asap_ordering,
        profile:orderTypesConfig:driveThruPickup:enableScheduledOrdering::boolean as enable_drive_thru_pickup_scheduled_ordering,
        profile:orderTypesConfig:pickup:enableASAPOrdering::boolean as enable_pickup_asap_ordering,
        profile:orderTypesConfig:pickup:enableScheduledOrdering::boolean as enable_pickup_scheduled_ordering,
        profile:paymentFees as payment_fees,
        profile:specialsSettings:discountBehavior::string as discount_behavior,
        profile:specialsSettings:discountStacking::boolean as has_discount_stacking,
        profile:storeSettings:defaultViewStyle::string as default_view_style,
        profile:storeSettings:disableGuestCheckout::boolean as disable_guest_checkout,
        profile:storeSettings:disableGuestDOB::boolean as disable_guest_dob,
        profile:storeSettings:disablePurchaseLimits::boolean as disable_purchase_limits,
        profile:storeSettings:displayBrands::boolean as display_brands,
        profile:storeSettings:displayPhoneConfirmation::boolean as display_phone_confirmation,
        profile:storeSettings:dontCombineWeightedProducts::boolean as dont_combine_product_weights,
        profile:storeSettings:enableAfterHoursOrderingForDelivery::boolean as enable_after_hours_ordering_for_delivery,
        profile:storeSettings:enableAfterHoursOrderingForPickup::boolean as enable_after_hours_ordering_for_pickup,
        profile:storeSettings:enableCustomerMessaging::boolean as enable_customer_messaging,
        profile:storeSettings:enableFeaturedProducts::boolean as enable_featured_products,
        profile:storeSettings:enableLimitPerCustomer::boolean as enable_limit_per_customer,
        profile:storeSettings:enableLLxSaleDiscountSync::boolean as enable_llx_sale_discount_sync,
        profile:storeSettings:enableMixAndMatchPricingForDelivery::boolean as enable_mix_and_match_pricing_for_delivery,
        profile:storeSettings:enableMixAndMatchPricingForPickup::boolean as enable_mix_and_match_pricing_for_pickup,
        profile:storeSettings:enableScheduledOrderingForDelivery::boolean as enable_scheduled_ordering_for_delivery,
        profile:storeSettings:enableScheduledOrderingForPickup::boolean as enable_scheduled_ordering_for_pickup,
        profile:storeSettings:enableV3::boolean as enable_v3,
        profile:storeSettings:expressCheckout::boolean as express_checkout,
        profile:storeSettings:hideAddressFromDutchieMain::boolean as hide_address_from_dutchie_main,
        profile:storeSettings:hideEffects::boolean as hide_effects,
        profile:storeSettings:hideFilters::boolean as hide_filters,
        profile:storeSettings:keepUncombinedWeights::boolean as keep_uncombined_weights,
        profile:storeSettings:requireEmailAddressForGuestCheckout::boolean as require_email_address_for_guest_checkout,
        profile:pauseOrders::boolean as pause_orders,
        profile:requireMedCardPhotoForDelivery::boolean as require_med_card_photo_for_delivery,
        profile:requireMedCardPhotoForPickup::boolean as require_med_card_photo_for_pickup,
        profile:storeSettings:stealthMode::boolean as stealth_mode,
        profile:storeSettings:subscriptions:enabled::boolean as subscriptions,
        profile:v3PreviouslyEnabled::boolean as v3_previously_enabled,
        profile:orderTypesConfig:curbsidePickup:enabled::boolean as offer_curbside_pickup,
        profile:orderTypesConfig:delivery:enabled::boolean as offer_delivery,
        profile:orderTypesConfig:driveThruPickup:enabled::boolean as offer_drive_thru_pickup,
        profile:orderTypesConfig:pickup:enabled::boolean as offer_pickup,
        profile:payOnlineHypur::boolean as pay_online_hypur,
        profile:payOnlineMerrco::boolean as pay_online_merrco,
        profile:medicalDispensary::boolean as medical_dispensary,
        profile:recDispensary::boolean as rec_dispensary,

            -- Misc

        emails,
        profile:phone::string as phone,
        profile:notes::string as notes,
        updated_at,
        _fivetran_synced,
        billing_notes,
        username,
        timezone,
        isolated_menus,
        apply_excise_to_pos,
        profile:bannerImage::string as banner_image,
        profile:logoImage::string as logo_image,
        profile:embeddedPageViews::number as embedded_page_views,
        round(profile:actionEstimates:delivery:readyInMinutes::number, 2) as delivery_estimate,
        round(profile:actionEstimates:pickup:readyInMinutes::number, 2) as pickup_estimate
    from
        stg_users
    left join
        account_executive
        on
            (account_executive.dispensary_id = stg_users._id)
    left join
        account_manager_primary
        on
            (account_manager_primary.dispensary_id = stg_users._id)
    left join
        account_manager_secondary
        on
            (account_manager_secondary.dispensary_id = stg_users._id)
    left join
        customer_success_manager
        on
            (customer_success_manager.dispensary_id = stg_users._id)
    left join
        pos_integrations
        on (pos_integrations.dispensary_id = stg_users._id)
    left join
        fleet_management_integrations
        on (fleet_management_integrations.dispensary_id = stg_users._id)
    left join
        payments_integrations
        on (payments_integrations.dispensary_id = stg_users._id)
    left join
        int__dispensary_list_integrations
        on (int__dispensary_list_integrations.dispensary_id = stg_users._id)
    left join
        int__dispensary_device_summary
        on (int__dispensary_device_summary.dispensary_id = stg_users._id)
    left join
        int__dispensaries_with_valid_specials
        on (int__dispensaries_with_valid_specials.dispensary_id = stg_users._id)
    left join
        paused_dispensaries
        on paused_dispensaries.dispensary_id = stg_users._id
    where
        profile:type = 'Dispensary'
)

select * from final
```

**Comment by barrywhart** [comment] 2022-01-21 21:58
@dwallace0723: Can you provide a complete example (models plus config files to reproduce this issue)? As I mentioned earlier, it's not possible to lint an ephemeral model directly, but linting another model that **depends on ** an ephemeral model should work. Above, I think you provided _just_ an ephemeral model.

Thanks!

**Comment by barrywhart** [comment] 2022-02-01 15:27
If I read your question correctly, you're trying to **directly** lint an ephemeral model, which is not supported. These models will be linted indirectly when other models use them. Closing this issue.

**Comment by barrywhart** [comment] 2022-02-01 20:53
Reopening this, because I realize we should look at whether the current behavior causes issues with pre-commit, where it attempts to modify all modified files. Ephemeral models are located in the same directory as normal models, so pre-commit will probably try and lint them whether ephemeral or not.

I don't think SQLFluff can actually lint these files, but it could likely handle the situation better:
* Print a reasonable warning or error message
* Don't return a failure code, because this in turn causes pre-commit to block committing

Could we (should we) allow working around this with "noqa"? Or just handle this automatically? 🤔

**Comment by barrywhart** [comment] 2022-03-01 02:26
Closing this issue after one month of no feedback. We've made some fixes to handling ephemeral models now. PR #2748 adds a dbt test case where it compiles 3 ephemeral models A, B, C, where A depends on B, which depends on C, so it _is_ possible to lint models that are purely ephemeral.

**Closed by barrywhart** 2022-03-01 02:26 UTC
Labels: bug, dbt, awaiting feedback
