### ISSUE TITLE
Unexpected alias resolution in subqueries - T-SQL

### ISSUE THREAD

**Issue by ianepreston** [sqlfluff/sqlfluff#2064] opened 2021-12-07 21:46 UTC
I noticed this issue when formatting a giant internal query and then comparing its results to the original query led to the formatted query breaking because an alias had been incorrectly replaced with the wrong table. The basic issue as near as I can tell was that the body of the main query aliased a table we'll call table1 as 'a' and then within a subquery a different table we'll call table2 was also aliased as 'a'. Not a great practice I know, but the query did execute as expected when run before formatting. After formatting the subquery replaced what should have been a reference to table2 with table1, which broke it. I've written a minimal example that illustrates some of the same behaviour.

## Expected Behaviour
Query should produce the same output before and after formatting
## Observed Behaviour
Query fails to run because of incorrect alias replacement
## Steps to Reproduce

Here's a minimal example of input sql that will demonstrate this result:

```sql
SELECT
    a.col1,
    (SELECT
        a.table1key,
        a.col1a,
        c.col1c
    FROM
        table2 AS a
        INNER JOIN table3 AS c ON a.key = c.table2key
    ) AS d
FROM
    table1 AS a,
    d
INNER JOIN ON a.key = d.table1key
```

and the output after I call format on it:

```sql
SELECT
    table1.col1,
    (SELECT
        table1.table1key,
        table2.col1a,
        table3.col1c
        FROM
            table2
        INNER JOIN table3 ON table2.key = c.table2key
    ) AS d
FROM
    table1,
    d
INNER JOIN ON a.key = d.table1key
```

As you can see the first column in the subquery is incorrectly identified as part of table1 when it should be table2 and also the inner join syntax is broken since we're no longer aliasing table3 as c, but the on statement still references c

## Dialect
T-SQL
## Version
sqlfluff 0.8.2
python 3.9.7

## Configuration
I haven't specified any configuration files for sqlfluff, so it would be whatever came with the package (installed via conda-forge). I'm happy to include any auto generated files if that's useful, just let me know what to include.

Thanks very much

**Comment by barrywhart** [comment] 2022-01-05 01:28
@ianepreston: I'm getting parse errors from this query. Are you seeing these as well? If I add parentheses around the `ON` clauses, it parses okay:
```
SELECT
    a.col1,
    (SELECT
        a.table1key,
        a.col1a,
        c.col1c
    FROM
        table2 AS a
        INNER JOIN table3 AS c ON (a.key = c.table2key)
    ) AS d
FROM
    table1 AS a,
    d
INNER JOIN ON (a.key = d.table1key)
```

With the parse errors fixed, I get the following result from running `sqlfluff fix`, which I think is correct.
```
SELECT
    table1.col1,
    (SELECT
        table2.table1key,
        table2.col1a,
        table3.col1c
        FROM
            table2
        INNER JOIN table3 ON (table1.key = table3.table2key)
    ) AS d
FROM
    table1,
    d
INNER JOIN ON(table1.key = d.table1key)
```

I agree this is a bug, just wanted to confirm you're seeing the parse error, also thinking this may be a lower priority issue if it only occurs when there's a parse error.

**Comment by rileyrunnoe** [comment] 2022-01-06 20:23
The bigquery dialect is also showing this error where the alias resolution becomes incorrect.

An aliased table in the overall selection but without a specific reference to that alias is removed, but the alias reference in the subquery still remains. This results in invalid bigquery sql.

Unfixed SQL:
```sql
SELECT col_1
, col_2
,col_3
from table_a AS a
WHERE NOT EXISTS (SELECT TRUE from table_b as b where a.col_4 = b.col_1)
```

"Fixed" SQL:
```sql
SELECT
    col_1
    , col_2
    , col_3
FROM table_a
WHERE NOT EXISTS (SELECT TRUE FROM table_b AS b WHERE a.col_4 = b.col_1)
```

**Comment by ianepreston** [comment] 2022-01-06 22:31
@barrywhart Thanks for following up. I do get a parse error as well if I run sqlfluff.parse on the statement:

```python
APIParsingError: Found 1 issues while parsing string.
Line 15, Position 1: Found unparsable section: 'INNER JOIN ON a.key = d.table1key'
```

Not to derail the topic, but should sqlfluff ensure it can parse a statement before it fixes it? Or at least issue a warning if it can't? I didn't think to run parse before running fix so I didn't get any error or warning that there might be issues.

Thanks very much.

**Comment by barrywhart** [comment] 2022-01-06 22:41
Yes, I think we are planning to change that. Often, applying fixes to SQL that won't parse does something useful, but overall it's too risky, and this is a good example of why. There's some recent discussion about it here: https://github.com/sqlfluff/sqlfluff/issues/2134

**Comment by ianepreston** [comment] 2022-01-06 23:43
You're way ahead of me. Thanks for the response!

**Comment by barrywhart** [comment] 2022-01-09 23:59
@rileyrunnoe: I think your comment is a separate issue: see #1462. The distinction is:
* This issue is talking about when SQLFluff **replaces** aliases with the actual table name in a `JOIN`.
* Issue #1462 talks about when SQLFluff **removes** what it thinks are unused aliases.

If this sounds correct to you, can you please add or move your example to #1462 instead?

**Comment by barrywhart** [comment] 2022-01-10 16:47
The TL;DR for this issue is, "sqlfluff fix' should not make changes if the file has parsing or templating errors". I'm going to close it because my understanding is that this is a duplicate of #2134 (see [this comment](https://github.com/sqlfluff/sqlfluff/issues/2134#issuecomment-1009099928) where I suggest changing the title of the issue to reflect what I think is the conclusion of the loonnnggg discussion).

**Closed** 2022-01-10 16:47 UTC
Labels: bug, fix corrupts sql, rule bug, awaiting feedback
