### ISSUE TITLE
L030: Auto-fix can produce broken SQL

### ISSUE THREAD

**Issue by dmohns** [sqlfluff/sqlfluff#3022] opened 2022-04-06 12:11 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

This is a very weird case, but running auto fix for L030 in this scenario produces broken SQL.

```
SELECT
    ROW_NUMBER(),
    `{{ params.project_id }}`.some_dataset._f_some_function(TRUE),
    `{{ params.project_id }}.some_dataset._f_some_function`(TRUE)
FROM `some_table`
;
```

### Expected Behaviour

I'm not even sure what I did expect as the output of L030. Probably this

```sql
SELECT
    ROW_NUMBER(),
    `{{ params.project_id }}`.some_dataset._F_SOME_FUNCTION(TRUE),
    `{{ params.project_id }}.some_dataset._f_some_function`(TRUE)
FROM `some_table`
;
```

### Observed Behaviour

```sql
SELECT
    ROW_NUMBER(),
    `{{ params.project_id }}`.some_dataset._F_SOME_FUNCTION_f_some_function(TRUE),
    `{{ params.project_id }}.some_dataset._f_some_function`(TRUE)
FROM `some_table`
;
```

Note the `_F_SOME_FUNCTION_f_some_function` part.

### How to reproduce

`sqlfluff fix --rules L030` on the example above

### Dialect

bigquery (not sure if it's related to bigquery)

### Version

Latest `main`

### Configuration

[sqlfluff]
templater = jinja
dialect = bigquery

[sqlfluff:templater:jinja:context]
params = {
    "project_id": "test_project",
    }

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment] 2022-04-06 12:22
Interestingly it does work without templated code.

i.e. fixing this:

```sql
SELECT
    ROW_NUMBER(),
    `project_id`.some_dataset._f_some_function(TRUE),
    `project_id.some_dataset._f_some_function`(TRUE)
FROM `some_table`
```

with this: `sqlfluff fix --dialect bigquery test.sql -f --rules L030`

produces this:

```sql
SELECT
    ROW_NUMBER(),
    `project_id`.some_dataset._F_SOME_FUNCTION(TRUE),
    `PROJECT_ID.SOME_DATASET._F_SOME_FUNCTION`(TRUE)
FROM `some_table`
```

**Comment by barrywhart** [comment] 2022-04-06 19:48
I took an initial look at this. My guess is that the bug is occurring during the patch generation phase. This happens after the fixes have been generated and applied, and SQLFluff is determining how to update the original source file. I say this because the logs (`-vvv`) from the `fix` command look correct (no duplication of the text).

Assigning this to myself.

I managed to reproduce this using the `ansi` dialect and a slightly simpler file:
```
SELECT RO(), {{ "t" }}.func()
```

**Comment by barrywhart** [comment] 2022-04-06 20:11
Confirmed that it's a bug in patch generation. These log messages are printed at the beginning of patch generation -- all is well at this point.
```
Persisting Changes...
DEBUG      Original Tree: 'SELECT RO(), t.func()\n'
DEBUG      Fixed Tree: 'SELECT RO(), t.FUNC()\n'
```

**Comment by barrywhart** [comment] 2022-04-06 20:33
As @tunetheweb guessed earlier, it seems to be having issues splitting apart the `FunctionNameSegment`, which spans two slices (templated and literal):
```
(Pdb) self
<FunctionNameSegment: ([L:  1, P: 14])>
(Pdb) self.pos_marker
PositionMarker(source_slice=slice(13, 27, None), templated_slice=slice(13, 19, None), templated_file=<TemplatedFile>, working_line_no=1, working_line_pos=14)
(Pdb) self.pos_marker.templated_file.source_str
'SELECT RO(), {{ "t" }}.func()\n'
(Pdb) self.pos_marker.templated_file.source_str[13:27]
'{{ "t" }}.func'
```

Later on, the `source_slice` for the corrected `FUNC` string is incorrect -- empty slice that should be the 4 characters `func`:
```
-> yield EnrichedFixPatch(
(Pdb) source_slice
slice(23, 23, None)
```

Empty source slice means we're **inserting** code, not **modifying**, hence the duplicated code.

**Closed** 2022-04-06 21:19 UTC
Labels: bug, templating, jinja, fix corrupts sql, rule bug
