### ISSUE TITLE
Bug in L031: Inappropriate fix applied when reference is templated.

### ISSUE THREAD

**Issue by sgoley** [sqlfluff/sqlfluff#937] opened 2021-04-07 23:11 UTC
When trying to use autofix linting errors, sqlfluff replaces model references with the compiled table reference.

### Expected Behaviour
dbt model refs shouldn't be replaced by their compiled values by the `fix` command.

### Observed Behaviour

When running `sqlfluff fix` on model, all dbt refs and aliases are replaced with compiled versions. 

New model contents:
```
SELECT `bigquery-project-123456`.`public`.`user`.id
       , cast(
        `bigquery-project-123456`.`public`.`user`.created_at AS timestamp
    ) AS created_at
    , cast(
        `bigquery-project-123456`.`public`.`user`.updated_at AS timestamp
    ) AS updated_at
    , `bigquery-project-123456`.`public`.`user`.user_id
    , `bigquery-project-123456`.`public`.`user`.partner_idr_id

FROM {{ source('public','user'_user
```

### Steps to Reproduce

Pre `sqlfluff fix` Model:

```
SELECT user.id,
       cast( user.created_at as timestamp) as created_at,
       cast( user.updated_at as timestamp) as updated_at,
       user.user_id,
       user.partner_id
FROM {{ source('public','user' ) }} as user
```

Try to fix using:

sqlfluff fix models/staging_tables/public/user.sql

output:

```
==== finding fixable violations ====
== [models\staging_tables\public\user.sql] FAIL
L:   1 | P:  23 | L019 | Found trailing comma. Expected only leading.
L:   2 | P:  37 | L010 | Inconsistent capitalisation of keywords.
L:   2 | P:  51 | L010 | Inconsistent capitalisation of keywords.
L:   2 | P:  64 | L019 | Found trailing comma. Expected only leading.
L:   3 | P:  36 | L010 | Inconsistent capitalisation of keywords.
L:   3 | P:  50 | L010 | Inconsistent capitalisation of keywords.
L:   3 | P:  63 | L019 | Found trailing comma. Expected only leading.
L:   4 | P:  25 | L019 | Found trailing comma. Expected only leading.
L:   6 | P:  52 | L010 | Inconsistent capitalisation of keywords.
L:   6 | P:  55 | L031 | Avoid using aliases in join condition
==== fixing violations ====
10 fixable linting violations found
Are you sure you wish to attempt to fix these? [Y/n] ...
Attempting fixes...
Persisting Changes...
== [models\staging_tables\public\user.sql] PASS
Done. Please check your files to confirm.
```

### Version

Include the output of sqlfluff --version along with your Python version

> python --version
Python 3.7.9

> sqlfluff --version
sqlfluff, version 0.5.0

> dbt --version
installed version: 0.18.1
   latest version: 0.19.1

### Configuration

> [sqlfluff]
> dialect = bigquery
> templater = dbt
> \# dbt templating does not keep trailing new lines (L009)
> exclude_rules = L009
> 
> [sqlfluff:templater:jinja]
> apply_dbt_builtins = True
> 
> [sqlfluff:rules]
> tab_space_size = 4
> max_line_length = 80
> indent_unit = space
> comma_style = leading
> allow_scalar = True
> single_table_references = consistent
> unquoted_identifiers_policy = all
> 
> [sqlfluff:rules:L010]  # Keywords
> capitalisation_policy = upper
> 
> [sqlfluff:rules:L014]  # Unquoted identifiers
> extended_capitalisation_policy = lower

**Comment by alanmcruickshank** [comment] 2021-04-08 11:18
This looks like a malfunction of L031: `Avoid using aliases in join condition`. Thanks for the bug report!

I don't think that L031 should flag if the main table reference is a templated field. i.e.

```
SELECT * FROM some_table_name as tbl  -- bad
SELECT * FROM {{ blah }} as tbl -- ok
```

@sgoley - you might want to deactivate L031 for now using `--exclude` or your config file. We'll get this fixed soon.

**Comment by philMarius** [comment] 2021-05-27 10:51
Any update on this? Would be good to ban aliases aside from in the case of using a DBT reference

**Comment by barrywhart** [comment] 2021-09-11 19:37
Can you provide a dbt project file and brief instructions how to reproduce the issue? When I use your SQL file and `.sqlfluff` file, I get the following error:

```
$ sqlfluff fix test.sql
dbt.exceptions.DbtProjectError: Runtime Error
  no dbt_project.yml found at expected path /Users/bhart/dev/sqlfluff/dbt_project.yml
```

**Comment by barrywhart** [comment] 2021-09-14 20:21
Attempting to reproduce this using the `jinja` templater.

`test.sql`:
```
SELECT u.id,
       cast( u.created_at as string),
       cast( u.updated_at as string),
       u.user_id,
       u.partner_id
FROM {{ source('pub','u' ) }} AS u
```

`.sqlfluff`:
```
[sqlfluff]
#rules = L003
templater = jinja
dialect = bigquery

[sqlfluff:templater:jinja:context]

[sqlfluff:templater:jinja:macros]
source = {% macro source(d, t) %} `{{d}}.{{t}}` {% endmacro %}
```

**Comment by barrywhart** [comment] 2021-09-14 20:22
This is the output I'm seeing.

```
SELECT
    `pub.u`.Id,
    cast( `pub.u`.Created_at AS string),
    cast( `pub.u`.Updated_at AS string),
    `pub.u`.User_id,
    `pub.u`.Partner_id
FROM {{ source('pub','u' ) }} AS u
```

Cannot reproduce this issue. Closing.

**Closed by barrywhart** 2021-09-14 20:22 UTC
Labels: bug, dbt, fix corrupts sql, awaiting feedback

**Comment by barrywhart** [comment] 2021-11-03 21:09
@kevinjmccarthy: I had closed this issue because I could not reproduce it. Please create a new issue with instructions to reproduce. Thanks!
