### ISSUE TITLE
Support for sqlite JSON functions

### ISSUE THREAD

**Issue by atishay** [sqlfluff/sqlfluff#5896] opened 2024-05-20 22:35 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

SQLite has JSON support turned on by default: https://www.sqlite.org/json1.html

The SQLite dialect needs to support `->>` and `->` operators.

### Use case

Need to support JSON based SQLite queries.

### Dialect

SQLite

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by Enduriel** [comment] 2024-05-21 08:54
@atishay are you planning to take a stab at this? I can add it to me todo when I need a change of pace otherwise 😅

**Comment by atishay** [comment] 2024-05-22 02:42
I set the dialect to MySQL to get through for now. I will see if I can get a PR up. Please add this to your Todo. If I work on this, I will have a PR up within this week, but I may find more issues as I try and enable sql fluff to my codebase.

**Comment by Enduriel** [comment] 2024-05-22 11:56
This seems to be a lot more painful than it should be. From my understanding the change should be as simple as adding the arrow operators to `BinaryOperatorGrammar` in sqlite, except this doesn't work because it seems to fail to parse earlier.

To me it seems like there's some matching order issue that I can't figure out, would probably need someone with more experience with the codebase to take a look.

To reproduce the issue add
```py
BinaryOperatorGrammar=OneOf(
    "->",
    "__",
),
```
to the end of
```py
sqlite_dialect.replace
```
in `src/sqlfluff/dialects/dialect_sqlite.py` and
```py
    "->",
    "__",
```
to `UNRESERVED_KEYWORDS` in `src/sqlfluff/dialects/dialect_sqlite_keywords`

sqlfluff will now parse
```
SELECT num __ 1 FROM t;
```
but not
```
SELECT num -> 1 FROM t;
```

(I'm aware this isn't the 'proper' way to add this functionality but wanted to remove as many variables as possible and this should definitely work)

**Comment by atishay** [comment] 2024-05-28 05:39
@Enduriel I tried my hand at it. Also have a few more PRs for features which were failing parsing in my codebase. Would love to get those in. Please help with the process.

**Comment by WittierDinosaur** [comment] 2024-08-24 12:50
Closing as fixed on main

**Closed by WittierDinosaur** 2024-08-24 12:50 UTC
Labels: enhancement, sqlite
