### ISSUE TITLE
Add `.sqlfluffignore` Configuration to `pyproject.toml`

### ISSUE THREAD

**Issue by nh916** [sqlfluff/sqlfluff#6036] opened 2024-08-01 20:57 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

Currently, `.sqlfluffignore` is used to specify files or directories that `sqlfluff` should skip over. However, it would be convenient to manage these ignore patterns directly within `pyproject.toml`, allowing all `sqlfluff` configurations to be centralized in a single file.

### Use case

Add support for a `[tool.sqlfluff.ignore]` section in `pyproject.toml` where users can specify the same ignore patterns that would typically go into a `.sqlfluffignore` file.

Example:

```toml
[tool.sqlfluff]
dialect = "ansi"
paths = ["./models"]

[tool.sqlfluff.ignore]
patterns = ["./venv", "./target"]
```

## Benefits

- **Centralized Configuration:** All sqlfluff settings are in one place.
- **Improved Workflow:** Avoids the need to manage separate .sqlfluffignore files.
- **Consistency:** Aligns with other tools using pyproject.toml for configuration.

I believe this enhancement would significantly improve sqlfluff usability and promote better project organization.

Thank you for considering this feature request.

### Dialect

All

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment] 2024-08-08 23:38
This is a duplicate of #5596

**Closed** 2024-09-17 13:02 UTC
Labels: enhancement
