### ISSUE TITLE
If I wanted to add custom rules...

### ISSUE THREAD

**Issue by SpokeyWheeler** [sqlfluff/sqlfluff#759] opened 2021-02-14 13:41 UTC
... should I add them in the "std" directory, with a different prefix? Or should I put them in a separate directory? 

What happens if I want to make "private" rules that I don't want to contribute?

Apologies for what are probably more dumb questions.

**Comment by barrywhart** [comment] 2021-02-14 14:35
There's a PR underway which will let you add rules in your own separate Python package.

 #705 

In the meantime, I guess you could fork the repo or just drop new rule files in the std directory after installation. There's not really a standard or approved way of doing it at this time.

**Comment by barrywhart** [comment] 2021-03-14 22:16
The PR mentioned above has been merged, addressing #164. I think this issue is a duplicate of that one. Leaving open for now in case there are questions.

**Comment by barrywhart** [comment] 2021-03-24 22:55
I'm going to close this issue. Feel free to ask questions in SQLFluff Slack or open another issue.

**Closed by barrywhart** 2021-03-24 22:55 UTC
Labels: duplicate, enhancement
