### ISSUE TITLE
"ValueError: Cannot instantiate a templated file unsliced!" error when processing jinja macros in dbt

### ISSUE THREAD

**Issue by fakhavan** [sqlfluff/sqlfluff#2947] opened 2022-03-30 00:36 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I use a solution similar to [this](https://discourse.getdbt.com/t/using-dbt-to-manage-user-defined-functions/18) to create UDFs in Snowflake and use them inside dbt models.

My current `create_udf.sql` looks like this:
```{% macro create_udfs() %}

{{ create_f_resolve_from_metadata() }};

{{ create_f_resolve_start_dt() }};

{{ create_f_resolve_end_dt() }};

{{ create_f_trim_to_null() }}

{% endmacro %}
```

`sqlfluff` raises an exception when trying to lint or fix this file:

```sqlfluff lint macros/create_udfs.sql --dialect snowflake
Traceback (most recent call last):
  File "/Users/farid/WorkSpace/Github_Repos/snowflake-dbt-transformations/.venv/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/Users/farid/WorkSpace/Github_Repos/snowflake-dbt-transformations/.venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/farid/WorkSpace/Github_Repos/snowflake-dbt-transformations/.venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/farid/WorkSpace/Github_Repos/snowflake-dbt-transformations/.venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/farid/WorkSpace/Github_Repos/snowflake-dbt-transformations/.venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/farid/WorkSpace/Github_Repos/snowflake-dbt-transformations/.venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/farid/WorkSpace/Github_Repos/snowflake-dbt-transformations/.venv/lib/python3.9/site-packages/sqlfluff/cli/commands.py", line 533, in lint
    result = lnt.lint_paths(
  File "/Users/farid/WorkSpace/Github_Repos/snowflake-dbt-transformations/.venv/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 1087, in lint_paths
    self.lint_path(
  File "/Users/farid/WorkSpace/Github_Repos/snowflake-dbt-transformations/.venv/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 1039, in lint_path
    for i, linted_file in enumerate(runner.run(fnames, fix), start=1):
  File "/Users/farid/WorkSpace/Github_Repos/snowflake-dbt-transformations/.venv/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 101, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/Users/farid/WorkSpace/Github_Repos/snowflake-dbt-transformations/.venv/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 54, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/Users/farid/WorkSpace/Github_Repos/snowflake-dbt-transformations/.venv/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 43, in iter_rendered
    yield fname, self.linter.render_file(fname, self.config)
  File "/Users/farid/WorkSpace/Github_Repos/snowflake-dbt-transformations/.venv/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 760, in render_file
    return self.render_string(raw_file, fname, config, encoding)
  File "/Users/farid/WorkSpace/Github_Repos/snowflake-dbt-transformations/.venv/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 731, in render_string
    templated_file, templater_violations = self.templater.process(
  File "/Users/farid/WorkSpace/Github_Repos/snowflake-dbt-transformations/.venv/lib/python3.9/site-packages/sqlfluff/core/templaters/jinja.py", line 389, in process
    TemplatedFile(
  File "/Users/farid/WorkSpace/Github_Repos/snowflake-dbt-transformations/.venv/lib/python3.9/site-packages/sqlfluff/core/templaters/base.py", line 94, in __init__
    raise ValueError("Cannot instantiate a templated file unsliced!")
ValueError: Cannot instantiate a templated file unsliced!
```

I get this behaviour both in the cli and the pre-commit hook. However, pasting the contents of the file into the online editor does not seem to return any exceptions and actually linting works on it.

### Expected Behaviour

To lint/fix the file and not raise any exceptions.

### Observed Behaviour

It raises an exception saying `ValueError: Cannot instantiate a templated file unsliced!`

### How to reproduce

Create a `.sql` file that contains jinja calls all over, similar to what I included in the above or the one in [the guide I used](https://discourse.getdbt.com/t/using-dbt-to-manage-user-defined-functions/18).

### Dialect

snowflake

### Version

`sqlfluff==0.11.2`
`dbt-snowflake==1.0.0`
`pre-commit 2.17.0`
`Python 3.9.12`

### Configuration

`.pre-commit-config.yaml`:
```repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 0.11.2
    hooks:
      - id: sqlfluff-lint
        args: ["--dialect", "snowflake", "--exclude-rules", "L003,L034,L037"]
        additional_dependencies: ["dbt-snowflake==1.0.0", "sqlfluff-templater-dbt"]
      - id: sqlfluff-fix
        args: ["--dialect", "snowflake", "--exclude-rules", "L003,L034,L037"]
        additional_dependencies: ["dbt-snowflake==1.0.0", "sqlfluff-templater-dbt"]
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment] 2022-03-30 18:27
The example file has `{% endmacro %}`, but there's no corresponding open tag. Is that correct?

**Comment by barrywhart** [comment] 2022-03-30 19:51
We can't reproduce this without more information. Your SQL file relies on macros that we don't have access to. You need to provide code and config files. If we can't reproduce it, we can't fix it.

**Comment by neo-kyleprigotzke** [comment] 2022-04-05 18:06
Error does appear to be when there isn't a {macro} at the start of the macro. Example of what will break/cause this error but still work in a dbt run;
`{% macro cents_to_dollars(column_name, precision=2) %}
regexp_replace(format_number({{ column_name }} / 100, {{ precision }}), ',', '')
{% endmacro %}`

What seems to prevent the issue is starting all macros with a `{macro}` like;
`{macro}
{% macro cents_to_dollars(column_name, precision=2) %}
regexp_replace(format_number({{ column_name }} / 100, {{ precision }}), ',', '')
{% endmacro %}`

**Comment by barrywhart** [comment] 2022-04-10 21:42
I think this is a duplicate of #3049. Since we don't have enough information to reproduce this problem, I'm closing the issue.

**Closed by barrywhart** 2022-04-10 21:42 UTC
Labels: bug, dbt, awaiting feedback
