### ISSUE TITLE
New Rule: where, having and quality - conditions on a new line

### ISSUE THREAD

**Issue by eetu-h** [sqlfluff/sqlfluff#2627] opened 2022-02-13 18:57 UTC
This is a suggestion for a new rule that is similar with Rule_L036.

In `where`, `having` and `qualify` clauses, conditions should be on a new line, unless there is only one condition

best practice 1:
 
```
select
    attr1,
    attr2
from db.tbl1
where
    attr3 = 'A' and
    attr4 = 'B'
```
    
best practice 2:
 
```
select
    attr1,
    attr2
from db.tbl1
where attr3 = 'A'
```

anti-pattern 1:
 
```
select
    attr1,
    attr2
from db.tbl1
where attr3 = 'A' and
    attr4 = 'B'
```
 
anti-pattern 2:
 
```
select
    attr1,
    attr2
from db.tbl1
where
    attr3 = 'A'
```
 
Would be nice, if it would be possible to force consistent formatting for `select` targets and `where`, `having` and `qualify` clauses.

**Comment by tunetheweb** [comment] 2022-02-15 00:44
I'm going to close this as a duplicate of #1247. It's not quite the same as they mention different clauses, but basically am extension of that ask.

Could you comment on that with you ask so this doesn't get forgotten?

**Closed by tunetheweb** 2022-02-15 00:44 UTC
Labels: enhancement
