### ISSUE TITLE
L067 incorrectly identifying semi-structured parsing

### ISSUE THREAD

**Issue by justincanney** [sqlfluff/sqlfluff#4533] opened 2023-03-15 19:19 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

When I run `sqlfluff fix --dialect snowflake` on the following line of code, I am getting a result that I do not expect
`p:"Page"::VARCHAR AS page,`
is being changed to:
`CAST(CAST(p AS :"Page") AS VARCHAR) AS page,`
I would have expected sqlfluff to pick up on [semi-structured parsing](https://docs.snowflake.com/en/user-guide/querying-semistructured#traversing-semi-structured-data), but it doesn't seem to
`sqlfluff lint` returns
`L067 | Inconsistent type casting styles found.`

### Expected Behaviour

I would expect sqlfluff to identify the single colon `:` as semi-structured parsing

### Observed Behaviour

Sqlfluff is incorrectly changing the single colon 

### How to reproduce

Run `sqlfluff fix --dialect snowflake` on the following line of code
`p:"Page"::VARCHAR AS page,`

### Dialect

snowflake

### Version

2.0.0a4

### Configuration

; This should be kept in sync with the .sqlfluff.ci file
; This .sqlfluff file is used for local development
[sqlfluff]
dialect = snowflake
templater = dbt
sql_file_exts = .sql,.sql.j2,.dml,.ddl
exclude_rules = L016, L031, L034

[sqlfluff:templater:jinja]
apply_dbt_builtins = True

[sqlfluff:templater:dbt]
project_dir = ./
profile = analytics_elt

[sqlfluff:rules:L010]
# Keywords Capitalization
capitalisation_policy = upper

[sqlfluff:rules:L030]
# Function Name Capitalization
extended_capitalisation_policy = upper

[sqlfluff:rules:L040]
# Null & Boolean Literals
capitalisation_policy = upper

[sqlfluff:rules:L063]
# Data Type Capitalization
extended_capitalisation_policy = upper

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment] 2023-03-20 21:20
This is a duplicate of #4453 and is solved on `main` by #4571.

**Closed by alanmcruickshank** 2023-03-20 21:20 UTC
Labels: bug
