### ISSUE TITLE
Use readable colors on terminal background

### ISSUE THREAD

**Issue by fmms** [sqlfluff/sqlfluff#3539] opened 2022-07-02 06:12 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

I am using sqlfluff in PowerShell.
PowerShell has by default a blue background.

The coloring of sqlfluff makes the output undreadable:
![image](https://user-images.githubusercontent.com/908734/176988957-561634f3-86d5-4433-a402-c9d4eb086ade.png)

### Use case

based on the background color of my terminal it should pick a color i can see.
Not sure, if the color of the terminal can be recognized, otherwise it might just have a different default for PowerShell.

### Dialect

all.

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment] 2022-07-02 10:46
Related to (or potentially even a duplicate of) #1170

Note you can use the `--nocolor` to completely stop colour output.

**Comment by fmms** [comment] 2022-07-02 10:57
@tunetheweb thanks did not find that one. Thanks for finding and thanks for this amazing project.
Let's close this as a duplicate of #1170

**Closed** 2022-07-02 10:58 UTC
Labels: enhancement, config options
