### ISSUE TITLE
Support Windows file encoding - UTF-8-BOM (and others)

### ISSUE THREAD

**Issue by nevado** [sqlfluff/sqlfluff#372] opened 2020-05-29 15:16 UTC
Hi,

When using sqlfluff lint on files in Windows that are encoded with UTF-8-BOM, every file starts with two errors because of the BOM character:

Unable to lex characters: ''\uefeff\nCREATE '...'
Found unparsable section: '\uefeff\nCREATE<text>...'

I don't believe there's any way to specify the encoding currently, would you be happy for me to try fixing this as below and submit a PR for it?

- add new entry in config.cfg for encoding, e.g. "encoding = utf-8-bom"
- use the configured encoding when reading files in linter.py::lint_path, https://github.com/alanmcruickshank/sqlfluff/blob/master/src/sqlfluff/linter.py#L873
- if config for encoding is not set, default to utf-8
- wrap in a try/except to catch invalid encodings
- add encoding=utf-8 to default_config.cfg?

Or better, is there a way to auto detect the encoding?

Thanks!

**Comment by alanmcruickshank** [comment] 2020-08-07 11:54
Happy for you to have a go at this one!

My preference (I think) would be that we do this as early in the process as possible, so that most functions can rely on a clean utf8 string downstream. Perhaps in the base `RawTemplaterInterface` or even in the file loading routines themselves.

The challenge here is that we'll also have to _re-encode_ the file in the `fix` commands. We'll probably have to store the encoding somewhere to do that.

Very happy to accept PRs on this!

**Comment by alanmcruickshank** [comment] 2021-02-19 19:17
I'm going to close this issue as it's effectively a duplicate of #654 - and that issue is slightly broader in scope. Any further discussion on this topic should happen there.

**Closed by alanmcruickshank** 2021-02-19 19:17 UTC
Labels: bug, enhancement, lexer, parser
