### ISSUE TITLE
add flag to make the funny ending of the CLI call optional

### ISSUE THREAD

**Issue by pandabrowski** [sqlfluff/sqlfluff#1270] opened 2021-08-12 15:09 UTC
the unicode characters at the end of the CLI call cause problems when it is executed in PyCharm as the external tool.
i'd expect a possiblity to turn it off.

**Comment by barrywhart** [comment] 2021-08-14 12:38
This is a duplicate of #1246, which has been addressed and will be in the next release. (0.6.3 or 0.7).

**Closed by barrywhart** 2021-08-14 12:38 UTC
Labels: enhancement
