### ISSUE TITLE
sqlfluff takes 20+ minutes when using dbt utils datespine

### ISSUE THREAD

**Issue by sdebruyn** [sqlfluff/sqlfluff#3378] opened 2022-05-20 08:13 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I have a CTE that looks like this:

```sql
Dates as (

    {{ dbt_utils.date_spine(
        datepart="day",
        start_date="cast('2020-01-01' as date)",
        end_date="cast(getdate() as date)"
        )
    }}

),
```

SQL fluff takes 20+ minutes to parse my file if this is included

### Expected Behaviour

< 1 minute parsing time

### Observed Behaviour

20+ minutes parsing time

### How to reproduce

Install dbt-utils in a project and use the CTE mentioned above.

### Dialect

T-SQL

### Version

sqlfluff-templater-dbt = "^0.13.1"
sqlfluff = "^0.13.1"

### Configuration

```
[tool.sqlfluff.core]
templater = "dbt"
dialect = "tsql"
exclude_rules = "L028,L009"

[tool.sqlfluff.rules]
max_line_length = 120

[tool.sqlfluff.rules.L010]
capitalisation_policy = "lower"

[tool.sqlfluff.rules.L014]
extended_capitalisation_policy = "pascal"

[tool.sqlfluff.templater.dbt]
project_dir = "dbt"
profiles_dir = "dbt"
profile = "default"
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment] 2022-05-20 14:59
Can you provide a way to reproduce this on postgres or sqlite? I don't have access to a tsql database.

Please provide dbt project file.

This is the error I'm getting:
```
  File "/usr/local/lib/python3.9/site-packages/dbt/adapters/postgres/connections.py", line 75, in exception_handler
    raise dbt.exceptions.DatabaseException(str(e).strip()) from e
dbt.exceptions.DatabaseException: Database Error
  function getdate() does not exist
  LINE 6:         ((cast(getdate() as date))::date - (cast('2020-01-01...
                         ^
  HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by barrywhart** [comment] 2022-05-20 15:02
Or if you could provide the compiled SQL file (after dbt renders it), that would be a good alternative.

Question: If you run `sqlfluff parse` on the compiled file, does that also take a long time? I'm wondering if this may be an issue with dbt or the database.

**Comment by tunetheweb** [comment] 2022-05-20 17:14
In postgres the way to get the current date is by using `CURRENT_DATE` (without brackets) so maybe a simple swap in of `GETDATE()` for that is the Postgres-equivalent?

**Comment by barrywhart** [comment] 2022-05-21 19:57
If I understand this macro correctly, it's building a very large SQL statement (hundreds of lines long, one line per day since January 2020). SQLFluff's parser tends to be slow with queries longer than 100-200 lines. As a workaround, I suggest you consider changing the date range and/or date part used when linting (rather than executing) to reduce the amount of SQL being processed.

@WittierDinosaur, @tunetheweb: Any thoughts on this issue? @WittierDinosaur: I think you said you may open some issues with ideas for speeding up parsing?

**Comment by sdebruyn** [comment] 2022-05-22 07:30
Sorry, was going to come back on this next Monday. You've figured it out correctly, it creates a 1000+ line file with 1 line for every date. Putting an ignore comment around the macro doesn't help since it is still getting parsed. At the moment we've put the file in .sqlfluffignore. Is there something in the configuration to parse the source files with the jinja instead of the rendered versions?

**Comment by WittierDinosaur** [comment] 2022-05-22 15:48
@barrywhart I'll put a set of issues together. @sdebruyn Yeah, unfortunately for now, we struggle with very big files. Parsing has come a long way in the last 6 months, but there's still plenty to improve upon. It is my top priority right now though!

**Comment by tunetheweb** [comment] 2022-05-22 15:59
From a linting point of view 1 line or 10 identical lines or 1000 identical lines are all the same. So one workaround would be to set the start date (or the end date) in a template variable and, for SQLFluff just make it really close to the end date. That way linting would be faster. Not sure if that’s an option here?

**Comment by barrywhart** [comment] 2022-11-26 03:06
For now, I suggest using `large_file_skip_byte_limit` to skip linting of large files. Someday, large files may parse more efficiently. Closing issue.

**Closed by barrywhart** 2022-11-26 03:06 UTC
Labels: enhancement, dbt, awaiting feedback
