### ISSUE TITLE
Add Merge Statement to ANSI Dialect (was: BigQuery dialect)

### ISSUE THREAD

**Issue by rileyrunnoe** [sqlfluff/sqlfluff#1125] opened 2021-06-02 18:52 UTC
Bigquery currently has the functionality to run [merge statments](https://cloud.google.com/bigquery/docs/reference/standard-sql/dml-syntax#merge_statement)

Hoping to add the necessary segments to allow for the parsing of BigQuery Merge statements.

This will allow the parsing of this type of SQL, opening up rule checks for rules that require parsing (like L003).

PS: This is my first issue submission here. Let me know if I am missing anything!

**Comment by barrywhart** [comment] 2021-06-02 19:25
I checked and confirmed that the BigQuery dialect currently does not support merge statements. I notice that the Exasol dialect already supports it.

Several other data stores in SQLFluff also support the merge statement (to be clear: the **databases** support it but the **SQLFluff dialects** do not). We should probably look at adding it to ANSI if the various dialects are relatively similar.
* [Postgres](https://www.postgresql.org/message-id/attachment/23520/sql-merge.html) 
* [Snowflake](https://docs.snowflake.com/en/sql-reference/sql/merge.html)
* [Exasol](https://docs.exasol.com/sql/merge.htm)
* [Teradata](https://docs.teradata.com/r/b8dd8xEYJnxfsq4uFRrHQQ/JWsxnf181RJeyTyvowuKHw)

AFAICT, MySQL does not support the merge statement, although it has something called the "merge engine". This is where I stopped reading -- because of the above, the details about MySQL probably don't matter. 😛

**Comment by PhilippLange** [comment] 2022-03-04 14:04
As I see there is no one actively working on this.
I might give this a try since I want to push #1936.
Who can assign this to me?

**Closed** 2022-03-08 15:55 UTC
Labels: enhancement, good first issue, dialect, bigquery

**Comment by rileyrunnoe** [comment] 2022-03-08 17:49
Thank you so much @PhilippLange!!

**Comment by PhilippLange** [comment] 2022-03-09 08:32
@rileyrunnoe no worries. However some BigQuery specific behavior is still missing:
[](https://github.com/sqlfluff/sqlfluff/pull/2807#discussion_r821775131)
