### ISSUE TITLE
dbt 1.6.14 breaks with ImportError: cannot import name 'read_user_config' from 'dbt.config'

### ISSUE THREAD

**Issue by anshjain18** [sqlfluff/sqlfluff#5851] opened 2024-05-06 07:00 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Started getting the error
`ImportError: cannot import name 'read_user_config' from 'dbt.config'`
while running sqlfluff on the dbt project.
Important thing to note is: we haven't done any version upgrade in both dbt and sqlfluff.
Other similar issues have been reported in dbt 1.7X only while we are still using dbt 1.6X

### Expected Behaviour

sqlfluff should work properly

### Observed Behaviour

ImportError is being thrown

### How to reproduce

Use the following versions:
dbt-core: 1.6.14
sqlfluff: 2.3.0
python: 3.11

### Dialect

ansi

### Version

sqlfluff-templater-dbt = 2.3.0
dbt = 1.6.14
python = 3.11

### Configuration

NA

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by kzajaczkowski** [comment] 2024-05-06 08:11
I am experiencing exactly the same error with dbt-core in version 1.7.14. It seems the same breaking changes (from sqlfluff perspective) were released in both 1.6.14 and 1.7.14.

**Comment by yuriidudar** [comment] 2024-05-06 08:40
I am experiencing the same issue with **dbt-core** in version `1.7.14`
To resolve this you need temporarily roll back **dbt-core** to `1.7.13` version

**Comment by anshjain18** [comment] 2024-05-06 09:03
@greg-finley I think the issue is that the new version of sqlfluff where this bug is fixed hasn't been published yet.
The latest version, 3.0.5 was released 2 weeks ago which doesn't seem like it has the fix included

**Comment by kzajaczkowski** [comment] 2024-05-06 09:17
Seems to be a dupe of 5841

**Comment by anshjain18** [comment] 2024-05-06 10:15
@kzajaczkowski  Yes, but that issue was closed and I don't think the problem is resolved yet

**Comment by WittierDinosaur** [comment] 2024-05-06 15:04
This is resolved in main - closing as duplicate.  I'll create a release candidate now, and we'll try to publish in the next 24 hours

**Closed by WittierDinosaur** 2024-05-06 15:04 UTC
Labels: bug

**Comment by lydialimlh** [comment] 2024-05-16 05:48
@anshjain18  Upgrading to v3.0.6 fixed the bug for me. Have a go at it?
