### ISSUE TITLE
Crash while parsing dbt SQL with macro

### ISSUE THREAD

**Issue by Olaktal** [sqlfluff/sqlfluff#2994] opened 2022-04-04 17:29 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Hello

I have a macro called `common_colum` that generate SQL (basically a list of columns) and when I use it, dbt crash.

SQL
```
SELECT {{ common_column_test(api.Relation.create(schema='fake_schema', identifier='plop')) }}
    raw_data.fake_column
FROM raw_data

```

I noticed that if a remove the last empty line (which line is requested by L009) it works but simply notice:
SQL
```
SELECT {{ common_column_test(api.Relation.create(schema='fake_schema', identifier='fake_identifier')) }}
    raw_data.fake_column
FROM raw_data
```
Result
```
L:   3 | P:  14 | L009 | Files must end with a single trailing newline.
```

Common column definition

```
{% macro common_column_test(table_relation) %}

    {% set common_column_csv -%}
    meta."versionId"::INT AS version_id,
    {%- endset %}

    {{ return(common_column_csv) }}
{% endmacro %}
```

Do you have any idea where it come from ?

thanks !

### Expected Behaviour

No crash

### Observed Behaviour

```
Traceback (most recent call last):
  File "/Users/vincentmartinez/.pyenv/versions/3.9.2/envs/data-engineering/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/Users/vincentmartinez/.pyenv/versions/3.9.2/envs/data-engineering/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/vincentmartinez/.pyenv/versions/3.9.2/envs/data-engineering/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/vincentmartinez/.pyenv/versions/3.9.2/envs/data-engineering/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/vincentmartinez/.pyenv/versions/3.9.2/envs/data-engineering/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/vincentmartinez/.pyenv/versions/3.9.2/envs/data-engineering/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/vincentmartinez/.pyenv/versions/3.9.2/envs/data-engineering/lib/python3.9/site-packages/sqlfluff/cli/commands.py", line 533, in lint
    result = lnt.lint_paths(
  File "/Users/vincentmartinez/.pyenv/versions/3.9.2/envs/data-engineering/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 1087, in lint_paths
    self.lint_path(
  File "/Users/vincentmartinez/.pyenv/versions/3.9.2/envs/data-engineering/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 1039, in lint_path
    for i, linted_file in enumerate(runner.run(fnames, fix), start=1):
  File "/Users/vincentmartinez/.pyenv/versions/3.9.2/envs/data-engineering/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 101, in run
    for fname, partial in self.iter_partials(fnames, fix=fix):
  File "/Users/vincentmartinez/.pyenv/versions/3.9.2/envs/data-engineering/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 54, in iter_partials
    for fname, rendered in self.iter_rendered(fnames):
  File "/Users/vincentmartinez/.pyenv/versions/3.9.2/envs/data-engineering/lib/python3.9/site-packages/sqlfluff/core/linter/runner.py", line 43, in iter_rendered
    yield fname, self.linter.render_file(fname, self.config)
  File "/Users/vincentmartinez/.pyenv/versions/3.9.2/envs/data-engineering/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 760, in render_file
    return self.render_string(raw_file, fname, config, encoding)
  File "/Users/vincentmartinez/.pyenv/versions/3.9.2/envs/data-engineering/lib/python3.9/site-packages/sqlfluff/core/linter/linter.py", line 731, in render_string
    templated_file, templater_violations = self.templater.process(
  File "/Users/vincentmartinez/.pyenv/versions/3.9.2/envs/data-engineering/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 323, in process
    processed_result = self._unsafe_process(fname_absolute_path, in_str, config)
  File "/Users/vincentmartinez/.pyenv/versions/3.9.2/envs/data-engineering/lib/python3.9/site-packages/sqlfluff_templater_dbt/templater.py", line 521, in _unsafe_process
    TemplatedFile(
  File "/Users/vincentmartinez/.pyenv/versions/3.9.2/envs/data-engineering/lib/python3.9/site-packages/sqlfluff/core/templaters/base.py", line 129, in __init__
    assert (
AssertionError
```

### How to reproduce

Use sql described above

### Dialect

redshift

### Version

```
sqlfluff, version 0.11.2
```

### Configuration

`.sqlfluff`
```
[sqlfluff]
templater = dbt
dialect = redshift
exclude_rules = L031

[sqlfluff:rules]
tab_space_size = 4
max_line_length = 800

[sqlfluff:rules:L029]
ignore_words = extension

[sqlfluff:rules:L059]
ignore_words = versionId,valueReference,valueCode,valueBoolean,valueString

[sqlfluff:templater:dbt]
project_dir = workflow/queries/dbt
library_path = dbt_utils
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by Olaktal** [comment] 2022-04-04 17:48
I think it is related to `api.Relation.create` because I have SQL files that use the same `common_column` function with `source(...)` as parameter instead of `api.Relation.create` without any error while linting

**Comment by barrywhart** [comment] 2022-04-06 19:22
Is this a duplicate of #2880?

**Comment by barrywhart** [comment] 2022-04-06 21:27
I tested on several recent versions of SQLFluff but cannot reproduce this. Closing, but will reopen if you can help us reproduce this. (I suspect you have an older version of core `sqlfluff` , as noted earlier.)

**Closed** 2022-04-06 21:27 UTC
Labels: bug, dbt, awaiting feedback

**Comment by Olaktal** [comment] 2022-04-12 08:52
My sqlfluff was 0.11.2 but my `sqlfluff-templater-dbt` was at a lower, that's why ! (I got it with a `poetry run pip freeze | grep sqlfluff`)
Thanks !
