### ISSUE TITLE
L003: Unfixable Jinja templates (auto fix loop) 

### ISSUE THREAD

**Issue by dmohns** [sqlfluff/sqlfluff#3185] opened 2022-04-26 10:15 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

On certain types of templated queries the auto fixer of L003 runs into a loop where indents can added and removed on each time the fix is run. The linter will always report a linting error and users have no other choice than ignoring the rule for that file (or line).

### Expected Behaviour

Stable behaviour of L003 with one result being considered "correct". This should also be the result of Auto Fix.

### Observed Behaviour

Take the following example:

```sql
{% for item in some_list -%}
    SELECT *
    FROM some_table
{{ "UNION ALL\n" if not loop.last }}
{%- endfor %}
```

The Autofix will indent line 4 to

```sql
{% for item in some_list -%}
    SELECT *
    FROM some_table
    {{ "UNION ALL\n" if not loop.last }}
{%- endfor %}
```

However, a second call will revert back to original.

### How to reproduce

Run lint/fix on

```sql
{% for item in some_list -%}
    SELECT *
    FROM some_table
{{ "UNION ALL\n" if not loop.last }}
{%- endfor %}
```

with the config provided below.

### Dialect

ansi

### Version

`main` branch from Github, commit `656a958146e9d415a39e77da7a063cd304fd56d3`

### Configuration

```
[sqlfluff:templater:jinja:context]
some_list = ["abc", "def"]
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment] 2022-05-06 21:13
When you log issues against the `main` branch in GitHub, please include the commit ID. Otherwise, it becomes difficult or impossible to reproduce issues reliably since `main` is constantly changing.

I'm seeing similar but not identical behavior at this commit: `77e283044c2a7d83db22f9df818cea96f8d2e0cb`. After the first `fix` run, it flips between this:
```
{% for item in [1, 2, 3] -%}
    SELECT *
    FROM some_table
{{ "UNION ALL\n" if not loop.last }}
{%- endfor %}
```
and this:
```
{% for item in [1, 2, 3] -%}
    SELECT *
    FROM some_table
    {{ "UNION ALL\n" if not loop.last }}
{%- endfor %}
```

**Comment by dmohns** [comment] 2022-05-07 08:28
Updated the description with the commit where I originally encountered this behaviour.

However, I'm able to reproduce the behaviour with the commit you mentioned (`77e283044c2a7d83db22f9df818cea96f8d2e0cb `). I.e.

Running `sqlfluff fix` on 

```sql
{% for item in [1, 2, 3] -%}
    SELECT *
    FROM some_table
{{ "UNION ALL\n" if not loop.last }}
{%- endfor %}
```

Produces

```sql
{% for item in [1, 2, 3] -%}
    SELECT *
    FROM some_table
    {{ "UNION ALL\n" if not loop.last }}
{%- endfor %}
```

(which I think is correct).

But then `sqlfluff lint` still reports a violation of L003 and running `sqlfluff fix` again produces

```sql
{% for item in [1, 2, 3] -%}
    SELECT *
    FROM some_table
{{ "UNION ALL\n" if not loop.last }}
{%- endfor %}
```

and we have the loop.

**Comment by barrywhart** [comment] 2022-05-07 15:48
@tunetheweb: Why is this marked as "enhancement to existing rule"?

**Comment by alanmcruickshank** [comment] 2022-10-07 12:31
Ah - I can see what's happening here.

It's because the line gets picked up twice, once in the loop and once outside (i.e. once when `loop.last` and once when not). I'm in L003 at the moment so I'll see if I can fix this.

**Comment by alanmcruickshank** [comment] 2022-10-27 23:08
I'm fairly confident that this is solved in my current working branch. The additional complexity here is that the `{% for ... -%}` loop consumes whitespace and complicates things somewhat. I think there's a solution to that part in #3999.

**Closed** 2022-12-19 10:54 UTC
Labels: bug, templating, jinja, enhancement to existing rule
