### ISSUE TITLE
Performance degradation noticed on sqlfluff v. 2.0.0x

### ISSUE THREAD

**Issue by nhrebinka** [sqlfluff/sqlfluff#4263] opened 2023-01-11 19:38 UTC
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

Our CI/CD runs sqlfluff v. 1.4.2 with `dbt` templater and it is already the slowest step of the process. It runs for about an hour on ~2900 files.  The goal is to switch to a slim CI, `diff-cover`, or anything similar.

While testing different versions I noticed a significant performance degradation in the versions `2.0.0a1` and `2.0.0a2` .

Attaching cprofiler files on different versions on a small portion of the sql files (29 out of ~2900)
Command for all of them is `python -m cProfile -s cumtime -m sqlfluff.cli.commands lint models/marts/health/pathways > 1.txt`
Attachements:
- `cprofile_sqlfluff_v_1.4.5_processes_0` --- all the processes (=8) on `1.4.5` on a small subset of files
- `cprofile_sqlfluff_v_1.4.5_processes_1` --- one process on `1.4.5` on a small subset of files
- `cprofile_sqlfluff_v_2.0.0a2_processes_0` --- all the processes (=8) on `2.0.0a2` on a small subset of files
- `cprofile_sqlfluff_v_2.0.0a2_processes_1` ---one process on `2.0.0a2` on a small subset of files
[cprofile_sqlfluff_v_1.4.5_processes_0.txt](https://github.com/sqlfluff/sqlfluff/files/10395481/cprofile_sqlfluff_v_1.4.5_processes_0.txt)
[cprofile_sqlfluff_v_1.4.5_processes_1.txt](https://github.com/sqlfluff/sqlfluff/files/10395482/cprofile_sqlfluff_v_1.4.5_processes_1.txt)
[cprofile_sqlfluff_v_2.0.0a2_processes_0.txt](https://github.com/sqlfluff/sqlfluff/files/10395483/cprofile_sqlfluff_v_2.0.0a2_processes_0.txt)
[cprofile_sqlfluff_v_2.0.0a2_processes_1.txt](https://github.com/sqlfluff/sqlfluff/files/10395484/cprofile_sqlfluff_v_2.0.0a2_processes_1.txt)

### Use case

I am trying to achieve a decent performance of our CICD 

### Dialect

dbt

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by nhrebinka** [comment] 2023-01-11 20:06
Not sure if I messed something up, just by looking at the stats it seems to be more or less the same.
It is probably not the version but overall slowness of dbt templater
~9 minutes to lint 29 files is slow.

```
-- 2.0.02a: 1 process
-- ==================
All Finished!
         476647240 function calls (446597331 primitive calls) in 708.940 seconds

-- 1.4.5: 1 process
-- =-==============
All Finished!
         447671643 function calls (418934872 primitive calls) in 721.209 seconds

-- 2.0.02a: 8 processes
-- =-==================
All Finished 
         4587137 function calls (4384034 primitive calls) in 565.116 seconds


-- 1.4.5: 8 processes
-- ==================
All Finished 
         4534393 function calls (4331841 primitive calls) in 536.265 seconds
```

**Comment by barrywhart** [comment] 2023-01-11 20:26
To measure the percentage slowdown, it may be more informative to look at the performance without the profiler. The profiler adds significant overhead, which tends to distort the difference (usually _understating_ the actual slowdown).

**Comment by barrywhart** [comment] 2023-01-11 20:28
You're using Snowflake, is that correct?

Would you potentially be able to share one or more of the slow files with us? If there's a concern about confidentiality, we could look at obfuscating the file (changing table names, column names, etc.). Just trying to think of ways that we can attack the problem more directly...

**Comment by nhrebinka** [comment] 2023-01-11 20:32
yup, it's Snowflake, and I will run the same without a profiler to measure the time and compare it.

I think it is not about the file length & complexity, it's about dbt calling Snowflake and trying to describe every single table, running `show terse` on every schema. Somehow `dbt compile` and `dbt run` needs less time than dbt-templater and sqlfluff. I will share the logs ones it is completed on both versions `1.4.5` and `2.0.0a2`

**Comment by barrywhart** [comment] 2023-01-11 20:47
I wonder if we could capture a profile of running `dbt compile`. If so, it'd be fascinating to compare that to the SQLFluff profile output. That could point directly to where things are going awry with SQLFluff.

**Comment by alanmcruickshank** [comment] 2023-01-12 15:06
I've been experiencing some slowness, but I assumed it was issues with parsing rather than the dbt plugin - I'll do some additional testing though.

**Comment by alanmcruickshank** [comment] 2023-01-12 16:15
Confirmed - the templating step in 2.0.0a2 is significantly slower in my environment (using the `--persist-timing` option). In linting a folder of models, the first linted file takes roughly 9s, which is very similar between the versions, but in `1.4.5` almost all other models take less than a second, but in `2.0.0a2` many are taking ~4s.

**Comment by alanmcruickshank** [comment] 2023-01-12 16:50
@barrywhart - from my debugging, I think the culprit is the clause which says:

```python
        if not osmosis_dbt_project:
            templater_logger.warning("GET OSMOSIS")
            if not self.profiles_dir:
                self.profiles_dir = self._get_profiles_dir()
            assert self.project_dir
            assert self.profiles_dir
            osmosis_dbt_project = self.dbt_project_container.add_project(
                project_dir=self.project_dir,
                profiles_dir=self.profiles_dir,
                vars=self._get_cli_vars(),
            )
```

I think the intent is that this doesn't run on every file, but it _is_ being called on every file, and it's the step which is taking the time (the rest is quite quick). @barrywhart - can you take a look at the caching of this? I assume we don't need to do as much reprocessing on each step.

**Comment by alanmcruickshank** [comment] 2023-01-12 17:24
To be clear - the bulk of the time is still spent in parsing, so this won't make everything lightning fast - but it is the part that is taking longer in 2.0.0a2.

**Comment by barrywhart** [comment] 2023-01-12 19:06
I'll take a look. Thanks for the initial investigation -- I don't use dbt in real life, so I often don't have good ways to find or confirm issues.

**Comment by nhrebinka** [comment] 2023-01-12 21:20
[dbt_cprof.zip](https://github.com/sqlfluff/sqlfluff/files/10406039/dbt_cprof.zip) Here is the cprofile on `dbt compile` on our super large project. If it helps in anyway to debug the issue. cProfile takes forever, `dbt compile` takes just minutes

It was doing `describe table` for at least 1-2 hours. I did not let it finish. Unzip it and run `snakeviz dbt.cprof` to view the file.
I hope it helps!

**Comment by barrywhart** [comment] 2023-01-13 15:41
@nhrebinka 

I looked into the dbt templater performance problem. The issue is specific to the new templater implementation we introduced recently. This is the one we _thought_ was faster. I wonder now if it was really faster, or if it was an accident or illusion during testing. 🤔

When I tried to fix the specific performance issue, it surfaced some other issues, so I decided to go back to the old implementation for now. We can try to move forward to the new implementation later. 

This is the PR which reverts those changes. Can you please test it and confirm if this gets us back to (approximately) the performance you saw in 1.4.2?
#4273

**Comment by WittierDinosaur** [comment] 2023-02-19 13:15
@nhrebinka @barrywhart's PR has been merged, so going to close this issue for now. If there's still substantial degradation, feel free to reopen!

**Closed by WittierDinosaur** 2023-02-19 13:15 UTC
Labels: enhancement
