### ISSUE TITLE
dbt lint/fix macro content.

### ISSUE THREAD

**Issue by bartlomiejolma** [sqlfluff/sqlfluff#1401] opened 2021-09-14 11:39 UTC
I have a dbt project setup and I want to run the sqlfluff against this project. The main problem that I have is that the majority of the SQL logic is encoded in the custom macros and in models I only have the config and the invocation of the custom macro
 Model:

```
{{ config(materialized='table') }}

SELECT
    *  FROM (({{ sample_macro() }}        ))
```

and simplified macro
```
{% macro sample_macro() %} 

SELECT a+b AS foo,
c AS bar from my_table

{% endmacro %} 
```
In real code all of the SQL that I want to lint is in macro, including calls to the dbt builtin macros (is_incremental) and some shared custom macros (e.g. conversion of time zone)
Is there a way to configure the project to lint the macro content?
I have tried with the following config

```
[sqlfluff]
dialect = snowflake
templater = dbt
ignore_templated_areas = False
```
But the sqlfluff fix can not fix the errors
```
Done. Some operations failed. Please check your files to confirm. Some errors cannot be fixed or there is another error blocking it.
```
I have also tried with explicitly linting/fixing the macro
```
sqlfluff lint macros/sample_macro.sql --verbose --templater jinja
````

But it did not find any issues:

```
sqlfluff parse macros/sample_macro.sql --verbose --templater jinja
==== sqlfluff ====
sqlfluff:                0.6.4 python:                 3.8.11
implementation:        cpython dialect:             snowflake
verbosity:                   1 templater:               jinja

=== [ path: macros/sample_macro.sql ] ===

[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    [META] placeholder:                                       [Type: 'compound', Raw: '{% macro sample_macro() %} \n\nSELECT a+b AS foo,\nc AS bar from my_table\n\n{% endmacro %}']
[L:  6, P: 15]      |    whitespace:                                               ' '
[L:  6, P: 16]      |    newline:                                                  '\n'

```

If I comment out the first and the last line of the macro linting works fine, but I wonder if there is a way to tell sqlfluff to ignore the jinja bits and focus only on SQL

```
sqlfluff lint macros/sample_macro.sql --verbose --templater jinja                                                     
==== sqlfluff ====
sqlfluff:                0.6.4 python:                 3.8.11
implementation:        cpython dialect:             snowflake
verbosity:                   1 templater:               jinja

==== readout ====

=== [ path: macros/sample_macro.sql ] ===
== [macros/sample_macro.sql] FAIL
L:   1 | P:   1 | L046 | Jinja tags should have a single whitespace on either
                       | side.
L:   3 | P:   1 | L034 | Use wildcards then simple targets before calculations
                       | and aggregates in select statements.
L:   3 | P:   1 | L036 | Select targets should be on a new line unless there is
                       | only one select target.
L:   3 | P:   9 | L006 | Missing whitespace before +
L:   3 | P:   9 | L006 | Missing whitespace after +
L:   4 | P:   1 | L003 | Indent expected and not found compared to line #3
L:   4 | P:  10 | L010 | Inconsistent capitalisation of keywords.
L:   6 | P:   1 | L046 | Jinja tags should have a single whitespace on either
                       | side.
==== summary ====
violations:        8 status:         FAIL
All Finished 📜 🎉!
```
## Expected Behaviour

Lint and fix the content of the macro

## Observed Behaviour

Failed to fix the template 

## Steps to Reproduce

As described in the model + macro above.

## Dialect
Snowflake + dbt

## Version
```
> sqlfluff --version
sqlfluff, version 0.6.5
```
## Configuration
```
[sqlfluff]
dialect = snowflake
templater = dbt
ignore_templated_areas = False
```

Slack discussion:
https://sqlfluff.slack.com/archives/C01GX4L213J/p1631277371044600

including some attempts with `--noqa`

**Comment by barrywhart** [comment] 2021-09-14 20:24
Can you please attach a zipped-up copy of a dbt project to reproduce this issue? Having this will make it easier for maintainers to 
reproduce and fix your issue. Thanks!

**Comment by bartlomiejolma** [comment] 2021-09-15 07:43
Sure!
[sample.zip](https://github.com/sqlfluff/sqlfluff/files/7167866/sample.zip)

**Comment by barrywhart** [comment] 2021-10-02 19:27
Changing this issue from "bug" to "enhancement". Looks like a good suggestion, but SQLFluff is working as designed for now, thus enhancement.

**Comment by barrywhart** [comment] 2022-02-01 20:49
Alex Higgs asked:
>Are there any plans to do clever things with stand-alone macros? With [dbtvault](https://github.com/Datavault-UK/dbtvault/) (the package) I'm looking at adding SQLFluff to, because it's 100% macros currently, I would need to create models specifically for linting. Basically a macro in dbtvault creates the sql for an entire table without need for anything else in the model. A model is just the macro call.
>I feel like something could be done with dbt operations, provided parameters via .sqlfluff to generate SQL purely from a macro and validate it maybe?

Me:
>Note that in general, a macro may expand to code that will not parse successfully:
>* To lint it, you need to know what kind of parameters to pass it
>* It may expand to something that is only part of a statement, e.g a WHERE clause
> Because of the need for custom scaffolding, this doesn't seem like something we'd want to try and build into SQLFluff. I could imagine sharing examples, techniques, and documentation for ways to do it, possibly providing some bits of helper code someday.

**Comment by barrywhart** [comment] 2022-03-01 02:28
I'm closing this issue. It seems pretty far beyond what SQLFluff is intended to do. My best recommendation would be to create test models that instantiate the macros. I get this isn't what you're asking for.

**Closed by barrywhart** 2022-03-01 02:28 UTC
Labels: enhancement, templating, dbt
